# -*- coding: utf-8 -*-
import scrapy
from scrapy.http import Request, FormRequest
from scrapy.selector import Selector
import json
import re

class TuniuSpider(scrapy.Spider):
    name = "tuniu_youji"

    custom_settings = {
        'DOWNLOAD_DELAY' : 0.3
    }

    youji_api = (
        (u'中国', u'丽江', u'http://trips.tuniu.com/travelthread/0/3312/%d/0', u'558'),
        (u'中国', u'北京', u'http://trips.tuniu.com/travelthread/0/200/%d/0', u'126'),
        (u'中国', u'阿坝', u'http://trips.tuniu.com/travelthread/0/2815/%d/0', u'215'),
        (u'中国', u'呼伦贝尔', u'http://trips.tuniu.com/travelthread/0/2107/%d/0', u'106'),
        (u'中国', u'杭州', u'http://trips.tuniu.com/travelthread/0/3402/%d/0', u'312'),
        (u'中国', u'昆明', u'http://trips.tuniu.com/travelthread/0/3302/%d/0', u'394'),
        (u'中国', u'武汉', u'http://trips.tuniu.com/travelthread/0/1402/%d/0', u'37'),
        (u'中国', u'大理', u'http://trips.tuniu.com/travelthread/0/3306/%d/0', u'258'),
        (u'中国', u'日照', u'http://trips.tuniu.com/travelthread/0/2415/%d/0', u'77'),
        (u'中国', u'黄山', u'http://trips.tuniu.com/travelthread/0/113/%d/0', u'243'),
        (u'中国', u'张家界', u'http://trips.tuniu.com/travelthread/0/1514/%d/0', u'249'),
        (u'中国', u'厦门', u'http://trips.tuniu.com/travelthread/0/414/%d/0', u'401'),
        (u'中国', u'成都', u'http://trips.tuniu.com/travelthread/0/2802/%d/0', u'304'),
        (u'中国', u'扬州', u'http://trips.tuniu.com/travelthread/0/1622/%d/0', u'56'),
        (u'中国', u'九江', u'http://trips.tuniu.com/travelthread/0/1708/%d/0', u'40'),
        (u'中国', u'三亚', u'http://trips.tuniu.com/travelthread/0/906/%d/0', u'545'),
        (u'中国', u'承德', u'http://trips.tuniu.com/travelthread/0/1006/%d/0', u'54'),
        (u'中国', u'郑州', u'http://trips.tuniu.com/travelthread/0/1202/%d/0', u'38'),
        (u'中国', u'香港', u'http://trips.tuniu.com/travelthread/0/1300/%d/0', u'95'),
        (u'中国', u'济南', u'http://trips.tuniu.com/travelthread/0/2402/%d/0', u'48'),
        (u'中国', u'长沙', u'http://trips.tuniu.com/travelthread/0/1502/%d/0', u'96'),
        (u'中国', u'迪庆', u'http://trips.tuniu.com/travelthread/0/3320/%d/0', u'379'),
        (u'中国', u'湘西', u'http://trips.tuniu.com/travelthread/0/1507/%d/0', u'193'),
        (u'中国', u'嘉兴', u'http://trips.tuniu.com/travelthread/0/3410/%d/0', u'66'),
        (u'中国', u'苏州', u'http://trips.tuniu.com/travelthread/0/1615/%d/0', u'180'),
        (u'中国', u'舟山', u'http://trips.tuniu.com/travelthread/0/3427/%d/0', u'54'),
        (u'中国', u'西宁', u'http://trips.tuniu.com/travelthread/0/2302/%d/0', u'63'),
        (u'中国', u'龙岩', u'http://trips.tuniu.com/travelthread/0/404/%d/0', u'46'),
        (u'中国', u'南投县', u'http://trips.tuniu.com/travelthread/0/2908/%d/0', u'41'),
        (u'中国', u'南平', u'http://trips.tuniu.com/travelthread/0/405/%d/0', u'46'),
        (u'中国', u'林芝', u'http://trips.tuniu.com/travelthread/0/3205/%d/0', u'196'),
        (u'中国', u'日喀则', u'http://trips.tuniu.com/travelthread/0/3207/%d/0', u'158'),
        (u'中国', u'桂林', u'http://trips.tuniu.com/travelthread/0/705/%d/0', u'320'),
        (u'中国', u'吉林', u'http://trips.tuniu.com/travelthread/0/1808/%d/0', u'47'),
        (u'中国', u'延边', u'http://trips.tuniu.com/travelthread/0/1812/%d/0', u'41'),
        (u'中国', u'南宁', u'http://trips.tuniu.com/travelthread/0/702/%d/0', u'55'),
        (u'中国', u'北海', u'http://trips.tuniu.com/travelthread/0/704/%d/0', u'57'),
        (u'中国', u'拉萨', u'http://trips.tuniu.com/travelthread/0/3202/%d/0', u'316'),
        (u'中国', u'晋中', u'http://trips.tuniu.com/travelthread/0/2612/%d/0', u'43'),
        (u'中国', u'西双版纳', u'http://trips.tuniu.com/travelthread/0/3318/%d/0', u'79'),
        (u'中国', u'乌鲁木齐', u'http://trips.tuniu.com/travelthread/0/3102/%d/0', u'53'),
        (u'中国', u'红河', u'http://trips.tuniu.com/travelthread/0/3308/%d/0', u'29'),
        (u'中国', u'怒江', u'http://trips.tuniu.com/travelthread/0/3313/%d/0', u'23'),
        (u'中国', u'庐山区', u'http://trips.tuniu.com/travelthread/0/1709/%d/0', u'36'),
        (u'中国', u'普洱', u'http://trips.tuniu.com/travelthread/0/3316/%d/0', u'55'),
        (u'中国', u'兰州', u'http://trips.tuniu.com/travelthread/0/502/%d/0', u'35'),
        (u'中国', u'敦煌市', u'http://trips.tuniu.com/travelthread/0/505/%d/0', u'61'),
        (u'中国', u'酒泉', u'http://trips.tuniu.com/travelthread/0/508/%d/0', u'27'),
        (u'中国', u'张掖', u'http://trips.tuniu.com/travelthread/0/515/%d/0', u'36'),
        (u'中国', u'呼和浩特', u'http://trips.tuniu.com/travelthread/0/2102/%d/0', u'68'),
        (u'中国', u'西城', u'http://trips.tuniu.com/travelthread/0/203/%d/0', u'90'),
        (u'中国', u'朝阳', u'http://trips.tuniu.com/travelthread/0/206/%d/0', u'97'),
        (u'中国', u'九寨沟县', u'http://trips.tuniu.com/travelthread/0/2811/%d/0', u'280'),
        (u'中国', u'海淀', u'http://trips.tuniu.com/travelthread/0/209/%d/0', u'124'),
        (u'中国', u'台北市', u'http://trips.tuniu.com/travelthread/0/2902/%d/0', u'105'),
        (u'中国', u'镇江', u'http://trips.tuniu.com/travelthread/0/1626/%d/0', u'33'),
        (u'中国', u'昆山市', u'http://trips.tuniu.com/travelthread/0/1631/%d/0', u'31'),
        (u'中国', u'香港岛', u'http://trips.tuniu.com/travelthread/0/1302/%d/0', u'340'),
        (u'中国', u'嘉义县', u'http://trips.tuniu.com/travelthread/0/2913/%d/0', u'29'),
        (u'中国', u'九龙半岛', u'http://trips.tuniu.com/travelthread/0/1303/%d/0', u'186'),
        (u'中国', u'花莲县', u'http://trips.tuniu.com/travelthread/0/2914/%d/0', u'36'),
        (u'中国', u'台东县', u'http://trips.tuniu.com/travelthread/0/2917/%d/0', u'24'),
        (u'中国', u'陇南', u'http://trips.tuniu.com/travelthread/0/512/%d/0', u'23'),
        (u'中国', u'大理市', u'http://trips.tuniu.com/travelthread/0/42244/%d/0', u'233'),
        (u'中国', u'凤凰县', u'http://trips.tuniu.com/travelthread/0/1516/%d/0', u'161'),
        (u'中国', u'广州', u'http://trips.tuniu.com/travelthread/0/602/%d/0', u'88'),
        (u'中国', u'深圳', u'http://trips.tuniu.com/travelthread/0/619/%d/0', u'66'),
        (u'中国', u'景德镇', u'http://trips.tuniu.com/travelthread/0/1706/%d/0', u'29'),
        (u'中国', u'上饶', u'http://trips.tuniu.com/travelthread/0/1711/%d/0', u'92'),
        (u'中国', u'贵阳', u'http://trips.tuniu.com/travelthread/0/802/%d/0', u'50'),
        (u'中国', u'威海', u'http://trips.tuniu.com/travelthread/0/2418/%d/0', u'29'),
        (u'中国', u'澳门', u'http://trips.tuniu.com/travelthread/0/2002/%d/0', u'82'),
        (u'中国', u'牡丹江', u'http://trips.tuniu.com/travelthread/0/1110/%d/0', u'39'),
        (u'中国', u'玄武区', u'http://trips.tuniu.com/travelthread/0/40680/%d/0', u'114'),
        (u'中国', u'玉山县', u'http://trips.tuniu.com/travelthread/0/41114/%d/0', u'41'),
        (u'中国', u'阿里', u'http://trips.tuniu.com/travelthread/0/3203/%d/0', u'71'),
        (u'中国', u'宁波', u'http://trips.tuniu.com/travelthread/0/3415/%d/0', u'97'),
        (u'中国', u'台州', u'http://trips.tuniu.com/travelthread/0/3424/%d/0', u'44'),
        (u'中国', u'那曲', u'http://trips.tuniu.com/travelthread/0/3206/%d/0', u'145'),
        (u'中国', u'渝中', u'http://trips.tuniu.com/travelthread/0/304/%d/0', u'56'),
        (u'中国', u'鼓浪屿风景区', u'http://trips.tuniu.com/travelthread/0/46289/%d/0', u'47'),
        (u'中国', u'亚龙湾', u'http://trips.tuniu.com/travelthread/0/46539/%d/0', u'255'),
        (u'中国', u'海棠湾镇', u'http://trips.tuniu.com/travelthread/0/47111/%d/0', u'215'),
        (u'中国', u'襄阳', u'http://trips.tuniu.com/travelthread/0/1416/%d/0', u'49'),
        (u'中国', u'海口', u'http://trips.tuniu.com/travelthread/0/902/%d/0', u'94'),
        (u'中国', u'黄浦', u'http://trips.tuniu.com/travelthread/0/2503/%d/0', u'99'),
        (u'中国', u'浦东新', u'http://trips.tuniu.com/travelthread/0/2515/%d/0', u'70'),
        (u'中国', u'常州', u'http://trips.tuniu.com/travelthread/0/1604/%d/0', u'38'),
        (u'中国', u'十堰', u'http://trips.tuniu.com/travelthread/0/1410/%d/0', u'24'),
        (u'中国', u'宜昌', u'http://trips.tuniu.com/travelthread/0/1418/%d/0', u'22'),
        (u'中国', u'哈尔滨', u'http://trips.tuniu.com/travelthread/0/1102/%d/0', u'100'),
        (u'中国', u'青岛', u'http://trips.tuniu.com/travelthread/0/2413/%d/0', u'115'),
        (u'中国', u'大同', u'http://trips.tuniu.com/travelthread/0/2604/%d/0', u'67'),
        (u'中国', u'太原', u'http://trips.tuniu.com/travelthread/0/2602/%d/0', u'79'),
        (u'中国', u'忻州', u'http://trips.tuniu.com/travelthread/0/2610/%d/0', u'43'),
        (u'中国', u'雅安', u'http://trips.tuniu.com/travelthread/0/2824/%d/0', u'48'),
        (u'中国', u'甘孜', u'http://trips.tuniu.com/travelthread/0/2812/%d/0', u'46'),
        (u'中国', u'焦作', u'http://trips.tuniu.com/travelthread/0/1206/%d/0', u'31'),
        (u'中国', u'西安', u'http://trips.tuniu.com/travelthread/0/2702/%d/0', u'132'),
        (u'中国', u'泰安', u'http://trips.tuniu.com/travelthread/0/2416/%d/0', u'33'),
        (u'中国', u'思明区', u'http://trips.tuniu.com/travelthread/0/40956/%d/0', u'430'),
        (u'中国', u'兴安', u'http://trips.tuniu.com/travelthread/0/40374/%d/0', u'33'),
        (u'中国', u'阿勒泰', u'http://trips.tuniu.com/travelthread/0/3104/%d/0', u'34'),
        (u'中国', u'邵阳', u'http://trips.tuniu.com/travelthread/0/1509/%d/0', u'27'),
        (u'中国', u'无锡', u'http://trips.tuniu.com/travelthread/0/1619/%d/0', u'129'),
        (u'中国', u'清远', u'http://trips.tuniu.com/travelthread/0/615/%d/0', u'24'),
        (u'中国', u'油尖旺区', u'http://trips.tuniu.com/travelthread/0/42721/%d/0', u'172'),
        (u'中国', u'东城', u'http://trips.tuniu.com/travelthread/0/202/%d/0', u'131'),
        (u'中国', u'福州', u'http://trips.tuniu.com/travelthread/0/402/%d/0', u'62'),
        (u'中国', u'金华', u'http://trips.tuniu.com/travelthread/0/3411/%d/0', u'52'),
        (u'中国', u'大连', u'http://trips.tuniu.com/travelthread/0/1906/%d/0', u'51'),
        (u'中国', u'绍兴', u'http://trips.tuniu.com/travelthread/0/3422/%d/0', u'89'),
        (u'中国', u'沈阳', u'http://trips.tuniu.com/travelthread/0/1902/%d/0', u'29'),
        (u'中国', u'湖州', u'http://trips.tuniu.com/travelthread/0/3409/%d/0', u'56'),
        (u'中国', u'衢州', u'http://trips.tuniu.com/travelthread/0/3419/%d/0', u'29'),
        (u'中国', u'烟台', u'http://trips.tuniu.com/travelthread/0/2419/%d/0', u'54'),
        (u'中国', u'高雄市', u'http://trips.tuniu.com/travelthread/0/2906/%d/0', u'62'),
        (u'中国', u'绵阳', u'http://trips.tuniu.com/travelthread/0/2816/%d/0', u'44'),
        (u'中国', u'三亚湾', u'http://trips.tuniu.com/travelthread/0/46540/%d/0', u'70'),
        (u'中国', u'温州', u'http://trips.tuniu.com/travelthread/0/3426/%d/0', u'43'),
        (u'中国', u'万宁', u'http://trips.tuniu.com/travelthread/0/908/%d/0', u'98'),
        (u'中国', u'周庄镇', u'http://trips.tuniu.com/travelthread/0/1627/%d/0', u'32'),
        (u'中国', u'宜宾', u'http://trips.tuniu.com/travelthread/0/2825/%d/0', u'35'),
        (u'中国', u'山南', u'http://trips.tuniu.com/travelthread/0/3208/%d/0', u'82'),
        (u'中国', u'台中市', u'http://trips.tuniu.com/travelthread/0/2905/%d/0', u'38'),
        (u'中国', u'峨眉山市', u'http://trips.tuniu.com/travelthread/0/2807/%d/0', u'62'),
        (u'中国', u'昌平', u'http://trips.tuniu.com/travelthread/0/214/%d/0', u'38'),
        (u'中国', u'泉州', u'http://trips.tuniu.com/travelthread/0/408/%d/0', u'24'),
        (u'中国', u'保亭', u'http://trips.tuniu.com/travelthread/0/919/%d/0', u'73'),
        (u'中国', u'茂县', u'http://trips.tuniu.com/travelthread/0/42005/%d/0', u'74'),
        (u'中国', u'武夷山市', u'http://trips.tuniu.com/travelthread/0/413/%d/0', u'52'),
        (u'中国', u'乐山', u'http://trips.tuniu.com/travelthread/0/2813/%d/0', u'41'),
        (u'中国', u'桃园县', u'http://trips.tuniu.com/travelthread/0/2915/%d/0', u'26'),
        (u'中国', u'大兴安岭', u'http://trips.tuniu.com/travelthread/0/1105/%d/0', u'28'),
        (u'中国', u'克拉玛依', u'http://trips.tuniu.com/travelthread/0/3112/%d/0', u'23'),
        (u'中国', u'陵水', u'http://trips.tuniu.com/travelthread/0/904/%d/0', u'45'),
        (u'中国', u'漳州', u'http://trips.tuniu.com/travelthread/0/415/%d/0', u'29'),
        (u'中国', u'琼海', u'http://trips.tuniu.com/travelthread/0/905/%d/0', u'32'),
        (u'中国', u'洛阳', u'http://trips.tuniu.com/travelthread/0/1210/%d/0', u'32'),
        (u'中国', u'桐庐县', u'http://trips.tuniu.com/travelthread/0/3435/%d/0', u'43'),
        (u'中国', u'咸阳', u'http://trips.tuniu.com/travelthread/0/2710/%d/0', u'31'),
        (u'中国', u'屏东县', u'http://trips.tuniu.com/travelthread/0/2907/%d/0', u'35'),
        (u'中国', u'朔州', u'http://trips.tuniu.com/travelthread/0/2605/%d/0', u'27'),
        (u'中国', u'白山', u'http://trips.tuniu.com/travelthread/0/1804/%d/0', u'31'),
        (u'中国', u'婺源', u'http://trips.tuniu.com/travelthread/0/46699/%d/0', u'37'),
        (u'中国', u'伊春', u'http://trips.tuniu.com/travelthread/0/1115/%d/0', u'24'),
        (u'中国', u'宝鸡', u'http://trips.tuniu.com/travelthread/0/2704/%d/0', u'24'),
        (u'中国', u'延庆', u'http://trips.tuniu.com/travelthread/0/219/%d/0', u'66'),
        (u'中国', u'安顺', u'http://trips.tuniu.com/travelthread/0/803/%d/0', u'36'),
        (u'中国', u'武隆', u'http://trips.tuniu.com/travelthread/0/327/%d/0', u'30'),
        (u'中国', u'延安', u'http://trips.tuniu.com/travelthread/0/2711/%d/0', u'25'),
        (u'中国', u'丰台', u'http://trips.tuniu.com/travelthread/0/207/%d/0', u'27'),
        (u'中国', u'黔东南', u'http://trips.tuniu.com/travelthread/0/806/%d/0', u'33'),
        (u'中国', u'婺源县', u'http://trips.tuniu.com/travelthread/0/1715/%d/0', u'75'),
        (u'中国', u'淳安县', u'http://trips.tuniu.com/travelthread/0/3418/%d/0', u'72'),
        (u'中国', u'上海', u'http://trips.tuniu.com/travelthread/0/2500/%d/0', u'88'),
        (u'中国', u'海南州', u'http://trips.tuniu.com/travelthread/0/42554/%d/0', u'81'),
        (u'中国', u'平遥县', u'http://trips.tuniu.com/travelthread/0/2614/%d/0', u'32'),
        (u'中国', u'陕西', u'http://trips.tuniu.com/travelthread/0/2700/%d/0', u'32'),
        (u'中国', u'重庆', u'http://trips.tuniu.com/travelthread/0/300/%d/0', u'29'),
        (u'中国', u'崇左', u'http://trips.tuniu.com/travelthread/0/41858/%d/0', u'27'),
        (u'中国', u'云南', u'http://trips.tuniu.com/travelthread/0/3300/%d/0', u'28'),
        (u'中国', u'保山', u'http://trips.tuniu.com/travelthread/0/3323/%d/0', u'24'),
        (u'中国', u'珠海', u'http://trips.tuniu.com/travelthread/0/628/%d/0', u'27'),
        (u'中国', u'海西', u'http://trips.tuniu.com/travelthread/0/42573/%d/0', u'30'),
        (u'中国', u'玉树', u'http://trips.tuniu.com/travelthread/0/42565/%d/0', u'24'),
        (u'中国', u'石景山', u'http://trips.tuniu.com/travelthread/0/208/%d/0', u'22'),
        (u'中国', u'南川', u'http://trips.tuniu.com/travelthread/0/341/%d/0', u'22'),
        (u'中国', u'怀化', u'http://trips.tuniu.com/travelthread/0/1506/%d/0', u'21'),
        (u'中国', u'安吉县', u'http://trips.tuniu.com/travelthread/0/3403/%d/0', u'22'),
        (u'中国', u'湘潭', u'http://trips.tuniu.com/travelthread/0/1510/%d/0', u'20'),
        (u'中国', u'包头', u'http://trips.tuniu.com/travelthread/0/2104/%d/0', u'21'),
        (u'中国', u'赤峰', u'http://trips.tuniu.com/travelthread/0/2105/%d/0', u'20'),
        (u'中国', u'池州', u'http://trips.tuniu.com/travelthread/0/109/%d/0', u'20'),
        (u'中国', u'甘南', u'http://trips.tuniu.com/travelthread/0/506/%d/0', u'26'),
        (u'中国', u'汉中', u'http://trips.tuniu.com/travelthread/0/2705/%d/0', u'20'),
        (u'中国', u'吐鲁番', u'http://trips.tuniu.com/travelthread/0/3118/%d/0', u'20'),
        (u'中国', u'岳阳', u'http://trips.tuniu.com/travelthread/0/1512/%d/0', u'19'),
        (u'中国', u'百色', u'http://trips.tuniu.com/travelthread/0/703/%d/0', u'20'),
        (u'中国', u'海北', u'http://trips.tuniu.com/travelthread/0/2307/%d/0', u'19'),
        (u'中国', u'保定', u'http://trips.tuniu.com/travelthread/0/1003/%d/0', u'20'),
        (u'中国', u'基隆市', u'http://trips.tuniu.com/travelthread/0/2903/%d/0', u'19'),
        (u'中国', u'泰州', u'http://trips.tuniu.com/travelthread/0/1617/%d/0', u'21'),
        (u'中国', u'嘉峪关', u'http://trips.tuniu.com/travelthread/0/516/%d/0', u'19'),
        (u'中国', u'榆林', u'http://trips.tuniu.com/travelthread/0/2712/%d/0', u'18'),
        (u'中国', u'阿拉善', u'http://trips.tuniu.com/travelthread/0/40394/%d/0', u'20'),
        (u'中国', u'台南市', u'http://trips.tuniu.com/travelthread/0/2904/%d/0', u'18'),
        (u'中国', u'渭南', u'http://trips.tuniu.com/travelthread/0/2706/%d/0', u'18'),
        (u'中国', u'神农架', u'http://trips.tuniu.com/travelthread/0/1412/%d/0', u'20'),
        (u'中国', u'昌吉', u'http://trips.tuniu.com/travelthread/0/3107/%d/0', u'17'),
        (u'中国', u'济宁', u'http://trips.tuniu.com/travelthread/0/2408/%d/0', u'17'),
        (u'中国', u'开封', u'http://trips.tuniu.com/travelthread/0/1208/%d/0', u'17'),
        (u'中国', u'蓬莱市', u'http://trips.tuniu.com/travelthread/0/2425/%d/0', u'24'),
        (u'中国', u'松江', u'http://trips.tuniu.com/travelthread/0/2517/%d/0', u'17'),
        (u'中国', u'淮安', u'http://trips.tuniu.com/travelthread/0/1606/%d/0', u'16'),
        (u'中国', u'秦皇岛', u'http://trips.tuniu.com/travelthread/0/1012/%d/0', u'18'),
        (u'中国', u'五指山', u'http://trips.tuniu.com/travelthread/0/910/%d/0', u'16'),
        (u'中国', u'昌都', u'http://trips.tuniu.com/travelthread/0/3204/%d/0', u'16'),
        (u'亚洲', u'普吉市', u'http://trips.tuniu.com/travelthread/0/785093/%d/0', u'213'),
        (u'亚洲', u'首尔', u'http://trips.tuniu.com/travelthread/0/43796/%d/0', u'286'),
        (u'亚洲', u'曼谷', u'http://trips.tuniu.com/travelthread/0/45398/%d/0', u'287'),
        (u'亚洲', u'马尔代夫', u'http://trips.tuniu.com/travelthread/0/3922/%d/0', u'347'),
        (u'亚洲', u'韩国', u'http://trips.tuniu.com/travelthread/0/3904/%d/0', u'391'),
        (u'亚洲', u'泰国', u'http://trips.tuniu.com/travelthread/0/3910/%d/0', u'512'),
        (u'亚洲', u'印度尼西亚', u'http://trips.tuniu.com/travelthread/0/3915/%d/0', u'286'),
        (u'亚洲', u'印度', u'http://trips.tuniu.com/travelthread/0/3919/%d/0', u'36'),
        (u'亚洲', u'芭环礁', u'http://trips.tuniu.com/travelthread/0/44288/%d/0', u'60'),
        (u'亚洲', u'尼泊尔', u'http://trips.tuniu.com/travelthread/0/3948/%d/0', u'88'),
        (u'亚洲', u'马来西亚', u'http://trips.tuniu.com/travelthread/0/3911/%d/0', u'198'),
        (u'亚洲', u'新加坡', u'http://trips.tuniu.com/travelthread/0/3912/%d/0', u'100'),
        (u'亚洲', u'土耳其', u'http://trips.tuniu.com/travelthread/0/3946/%d/0', u'104'),
        (u'亚洲', u'日本', u'http://trips.tuniu.com/travelthread/0/3905/%d/0', u'295'),
        (u'亚洲', u'菲律宾', u'http://trips.tuniu.com/travelthread/0/3914/%d/0', u'223'),
        (u'亚洲', u'柬埔寨', u'http://trips.tuniu.com/travelthread/0/3908/%d/0', u'235'),
        (u'亚洲', u'越南', u'http://trips.tuniu.com/travelthread/0/3906/%d/0', u'90'),
        (u'亚洲', u'阿拉伯联合酋长国', u'http://trips.tuniu.com/travelthread/0/3936/%d/0', u'82'),
        (u'亚洲', u'斯里兰卡', u'http://trips.tuniu.com/travelthread/0/3920/%d/0', u'30'),
        (u'亚洲', u'沙迦', u'http://trips.tuniu.com/travelthread/0/42839/%d/0', u'34'),
        (u'亚洲', u'暹粒市', u'http://trips.tuniu.com/travelthread/0/785095/%d/0', u'188'),
        (u'亚洲', u'恰纳卡莱', u'http://trips.tuniu.com/travelthread/0/1742919/%d/0', u'27'),
        (u'亚洲', u'吉隆坡', u'http://trips.tuniu.com/travelthread/0/44331/%d/0', u'67'),
        (u'亚洲', u'胡志明市', u'http://trips.tuniu.com/travelthread/0/46127/%d/0', u'55'),
        (u'亚洲', u'迪拜', u'http://trips.tuniu.com/travelthread/0/42838/%d/0', u'117'),
        (u'亚洲', u'马莱', u'http://trips.tuniu.com/travelthread/0/786666/%d/0', u'100'),
        (u'亚洲', u'巴厘岛', u'http://trips.tuniu.com/travelthread/0/784812/%d/0', u'230'),
        (u'亚洲', u'吉隆坡市', u'http://trips.tuniu.com/travelthread/0/44332/%d/0', u'58'),
        (u'亚洲', u'伊斯坦布尔', u'http://trips.tuniu.com/travelthread/0/45564/%d/0', u'60'),
        (u'亚洲', u'马累北环礁', u'http://trips.tuniu.com/travelthread/0/44283/%d/0', u'237'),
        (u'亚洲', u'巴格马蒂', u'http://trips.tuniu.com/travelthread/0/44996/%d/0', u'36'),
        (u'亚洲', u'登巴萨', u'http://trips.tuniu.com/travelthread/0/784806/%d/0', u'53'),
        (u'亚洲', u'卡夫阿里夫环礁', u'http://trips.tuniu.com/travelthread/0/44277/%d/0', u'115'),
        (u'亚洲', u'诺鲁环礁', u'http://trips.tuniu.com/travelthread/0/44289/%d/0', u'85'),
        (u'亚洲', u'亚里南环礁', u'http://trips.tuniu.com/travelthread/0/44286/%d/0', u'116'),
        (u'亚洲', u'东京市', u'http://trips.tuniu.com/travelthread/0/785057/%d/0', u'224'),
        (u'亚洲', u'妮兰朵南环礁', u'http://trips.tuniu.com/travelthread/0/44290/%d/0', u'52'),
        (u'亚洲', u'京都市', u'http://trips.tuniu.com/travelthread/0/47164/%d/0', u'166'),
        (u'亚洲', u'大阪市', u'http://trips.tuniu.com/travelthread/0/784018/%d/0', u'177'),
        (u'亚洲', u'富士宫市', u'http://trips.tuniu.com/travelthread/0/784909/%d/0', u'129'),
        (u'亚洲', u'新加坡市', u'http://trips.tuniu.com/travelthread/0/47109/%d/0', u'134'),
        (u'亚洲', u'神奈川', u'http://trips.tuniu.com/travelthread/0/784001/%d/0', u'90'),
        (u'亚洲', u'南都留郡', u'http://trips.tuniu.com/travelthread/0/784935/%d/0', u'71'),
        (u'亚洲', u'东京', u'http://trips.tuniu.com/travelthread/0/45103/%d/0', u'77'),
        (u'亚洲', u'奈良市', u'http://trips.tuniu.com/travelthread/0/784945/%d/0', u'45'),
        (u'亚洲', u'西米沙鄢', u'http://trips.tuniu.com/travelthread/0/784028/%d/0', u'144'),
        (u'亚洲', u'济州市', u'http://trips.tuniu.com/travelthread/0/784029/%d/0', u'204'),
        (u'亚洲', u'西归浦市', u'http://trips.tuniu.com/travelthread/0/785079/%d/0', u'147'),
        (u'亚洲', u'济州岛', u'http://trips.tuniu.com/travelthread/0/43660/%d/0', u'181'),
        (u'亚洲', u'甲米', u'http://trips.tuniu.com/travelthread/0/784623/%d/0', u'87'),
        (u'亚洲', u'芭提雅', u'http://trips.tuniu.com/travelthread/0/784026/%d/0', u'195'),
        (u'亚洲', u'马累南环礁', u'http://trips.tuniu.com/travelthread/0/44284/%d/0', u'94'),
        (u'亚洲', u'美慕环礁', u'http://trips.tuniu.com/travelthread/0/44280/%d/0', u'53'),
        (u'亚洲', u'哈阿里夫环礁', u'http://trips.tuniu.com/travelthread/0/44273/%d/0', u'49'),
        (u'亚洲', u'清迈', u'http://trips.tuniu.com/travelthread/0/45412/%d/0', u'53'),
        (u'亚洲', u'清迈市', u'http://trips.tuniu.com/travelthread/0/784710/%d/0', u'55'),
        (u'亚洲', u'加德满都', u'http://trips.tuniu.com/travelthread/0/786170/%d/0', u'44'),
        (u'亚洲', u'西努环礁', u'http://trips.tuniu.com/travelthread/0/44271/%d/0', u'43'),
        (u'亚洲', u'普吉', u'http://trips.tuniu.com/travelthread/0/45410/%d/0', u'29'),
        (u'亚洲', u'亚里北环礁', u'http://trips.tuniu.com/travelthread/0/44272/%d/0', u'30'),
        (u'亚洲', u'代尼兹利', u'http://trips.tuniu.com/travelthread/0/1742859/%d/0', u'27'),
        (u'亚洲', u'阿布扎比', u'http://trips.tuniu.com/travelthread/0/42836/%d/0', u'30'),
        (u'亚洲', u'金边市', u'http://trips.tuniu.com/travelthread/0/43977/%d/0', u'27'),
        (u'亚洲', u'甘达基', u'http://trips.tuniu.com/travelthread/0/44998/%d/0', u'24'),
        (u'亚洲', u'富士吉田市', u'http://trips.tuniu.com/travelthread/0/784688/%d/0', u'26'),
        (u'亚洲', u'名古屋市', u'http://trips.tuniu.com/travelthread/0/47148/%d/0', u'36'),
        (u'亚洲', u'马六甲市', u'http://trips.tuniu.com/travelthread/0/44334/%d/0', u'32'),
        (u'亚洲', u'拜县', u'http://trips.tuniu.com/travelthread/0/784732/%d/0', u'24'),
        (u'亚洲', u'河内', u'http://trips.tuniu.com/travelthread/0/46126/%d/0', u'27'),
        (u'亚洲', u'伊兹密尔省', u'http://trips.tuniu.com/travelthread/0/1742916/%d/0', u'21'),
        (u'亚洲', u'文莱', u'http://trips.tuniu.com/travelthread/0/3913/%d/0', u'23'),
        (u'亚洲', u'岛原市', u'http://trips.tuniu.com/travelthread/0/785055/%d/0', u'21'),
        (u'亚洲', u'横滨市', u'http://trips.tuniu.com/travelthread/0/784000/%d/0', u'21'),
        (u'亚洲', u'京都', u'http://trips.tuniu.com/travelthread/0/45114/%d/0', u'22'),
        (u'亚洲', u'奈良', u'http://trips.tuniu.com/travelthread/0/45118/%d/0', u'23'),
        (u'亚洲', u'马德望市', u'http://trips.tuniu.com/travelthread/0/785133/%d/0', u'23'),
        (u'亚洲', u'安卡拉', u'http://trips.tuniu.com/travelthread/0/1743000/%d/0', u'20'),
        (u'亚洲', u'冲绳', u'http://trips.tuniu.com/travelthread/0/45097/%d/0', u'19'),
        (u'亚洲', u'札幌市', u'http://trips.tuniu.com/travelthread/0/47150/%d/0', u'22'),
        (u'亚洲', u'仁川', u'http://trips.tuniu.com/travelthread/0/43795/%d/0', u'21'),
        (u'亚洲', u'特拉布宗', u'http://trips.tuniu.com/travelthread/0/45553/%d/0', u'18'),
        (u'亚洲', u'大野郡', u'http://trips.tuniu.com/travelthread/0/784882/%d/0', u'19'),
        (u'亚洲', u'小樽市', u'http://trips.tuniu.com/travelthread/0/47179/%d/0', u'20'),
        (u'亚洲', u'哥打基纳巴鲁', u'http://trips.tuniu.com/travelthread/0/44388/%d/0', u'20'),
        (u'亚洲', u'巴德岗', u'http://trips.tuniu.com/travelthread/0/1800181/%d/0', u'19'),
        (u'亚洲', u'达瓜巴', u'http://trips.tuniu.com/travelthread/0/784700/%d/0', u'19'),
        (u'亚洲', u'釜山', u'http://trips.tuniu.com/travelthread/0/43658/%d/0', u'19'),
        (u'亚洲', u'北海道', u'http://trips.tuniu.com/travelthread/0/45095/%d/0', u'18'),
        (u'亚洲', u'富山', u'http://trips.tuniu.com/travelthread/0/45107/%d/0', u'18'),
        (u'亚洲', u'沙巴', u'http://trips.tuniu.com/travelthread/0/44378/%d/0', u'18'),
        (u'亚洲', u'下龙市', u'http://trips.tuniu.com/travelthread/0/784184/%d/0', u'22'),
        (u'亚洲', u'老挝', u'http://trips.tuniu.com/travelthread/0/3907/%d/0', u'16'),
        (u'亚洲', u'登别市', u'http://trips.tuniu.com/travelthread/0/47176/%d/0', u'15'),
        (u'亚洲', u'大城', u'http://trips.tuniu.com/travelthread/0/45377/%d/0', u'15'),
        (u'亚洲', u'兰卡威', u'http://trips.tuniu.com/travelthread/0/44313/%d/0', u'14'),
        (u'亚洲', u'是拉差', u'http://trips.tuniu.com/travelthread/0/784605/%d/0', u'14'),
        (u'亚洲', u'芽庄市', u'http://trips.tuniu.com/travelthread/0/784198/%d/0', u'18'),
        (u'亚洲', u'福冈市', u'http://trips.tuniu.com/travelthread/0/47153/%d/0', u'24'),
        (u'亚洲', u'罗勇', u'http://trips.tuniu.com/travelthread/0/784625/%d/0', u'13'),
        (u'亚洲', u'金泽市', u'http://trips.tuniu.com/travelthread/0/785011/%d/0', u'16'),
        (u'亚洲', u'拉薇雅尼环礁', u'http://trips.tuniu.com/travelthread/0/44278/%d/0', u'12'),
        (u'亚洲', u'伊兹密尔', u'http://trips.tuniu.com/travelthread/0/45565/%d/0', u'12'),
        (u'亚洲', u'大阪', u'http://trips.tuniu.com/travelthread/0/45099/%d/0', u'12'),
        (u'亚洲', u'文冬', u'http://trips.tuniu.com/travelthread/0/44350/%d/0', u'13'),
        (u'亚洲', u'坡州市', u'http://trips.tuniu.com/travelthread/0/43704/%d/0', u'12'),
        (u'亚洲', u'马尼拉', u'http://trips.tuniu.com/travelthread/0/43502/%d/0', u'12'),
        (u'亚洲', u'清莱', u'http://trips.tuniu.com/travelthread/0/45411/%d/0', u'12'),
        (u'亚洲', u'静冈', u'http://trips.tuniu.com/travelthread/0/45115/%d/0', u'13'),
        (u'亚洲', u'苏梅', u'http://trips.tuniu.com/travelthread/0/784722/%d/0', u'15'),
        (u'亚洲', u'斯里巴加湾', u'http://trips.tuniu.com/travelthread/0/785766/%d/0', u'16'),
        (u'亚洲', u'攀牙', u'http://trips.tuniu.com/travelthread/0/45407/%d/0', u'11'),
        (u'亚洲', u'御殿场市', u'http://trips.tuniu.com/travelthread/0/784927/%d/0', u'11'),
        (u'亚洲', u'纳拉亚尼', u'http://trips.tuniu.com/travelthread/0/45006/%d/0', u'10'),
        (u'亚洲', u'拉环礁', u'http://trips.tuniu.com/travelthread/0/44274/%d/0', u'14'),
        (u'亚洲', u'巴拉旺省', u'http://trips.tuniu.com/travelthread/0/785760/%d/0', u'10'),
        (u'亚洲', u'内夫谢希尔', u'http://trips.tuniu.com/travelthread/0/1742891/%d/0', u'11'),
        (u'亚洲', u'槟城', u'http://trips.tuniu.com/travelthread/0/44297/%d/0', u'10'),
        (u'亚洲', u'拉贾斯坦邦', u'http://trips.tuniu.com/travelthread/0/786925/%d/0', u'9'),
        (u'亚洲', u'以色列', u'http://trips.tuniu.com/travelthread/0/3944/%d/0', u'9'),
        (u'亚洲', u'阿格拉', u'http://trips.tuniu.com/travelthread/0/786733/%d/0', u'10'),
        (u'亚洲', u'保和岛', u'http://trips.tuniu.com/travelthread/0/784037/%d/0', u'9'),
        (u'亚洲', u'会安市', u'http://trips.tuniu.com/travelthread/0/784188/%d/0', u'13'),
        (u'亚洲', u'鹿儿岛', u'http://trips.tuniu.com/travelthread/0/45117/%d/0', u'12'),
        (u'亚洲', u'锡吉里耶', u'http://trips.tuniu.com/travelthread/0/1800002/%d/0', u'9'),
        (u'亚洲', u'全罗南道', u'http://trips.tuniu.com/travelthread/0/43772/%d/0', u'8'),
        (u'亚洲', u'安塔利亚', u'http://trips.tuniu.com/travelthread/0/45505/%d/0', u'8'),
        (u'亚洲', u'琅勃拉邦', u'http://trips.tuniu.com/travelthread/0/786604/%d/0', u'8'),
        (u'亚洲', u'福冈', u'http://trips.tuniu.com/travelthread/0/45105/%d/0', u'8'),
        (u'亚洲', u'清莱市', u'http://trips.tuniu.com/travelthread/0/784708/%d/0', u'10'),
        (u'亚洲', u'神户市', u'http://trips.tuniu.com/travelthread/0/47158/%d/0', u'11'),
        (u'亚洲', u'科伦坡', u'http://trips.tuniu.com/travelthread/0/786338/%d/0', u'7'),
        (u'亚洲', u'象岛', u'http://trips.tuniu.com/travelthread/0/1792199/%d/0', u'7'),
        (u'亚洲', u'千叶', u'http://trips.tuniu.com/travelthread/0/45122/%d/0', u'7'),
        (u'亚洲', u'黑部市', u'http://trips.tuniu.com/travelthread/0/47170/%d/0', u'7'),
        (u'亚洲', u'瓦拉纳西', u'http://trips.tuniu.com/travelthread/0/786727/%d/0', u'7'),
        (u'亚洲', u'长崎市', u'http://trips.tuniu.com/travelthread/0/785045/%d/0', u'7'),
        (u'亚洲', u'艾登', u'http://trips.tuniu.com/travelthread/0/1742837/%d/0', u'7'),
        (u'亚洲', u'万荣', u'http://trips.tuniu.com/travelthread/0/786630/%d/0', u'7'),
        (u'亚洲', u'箱根', u'http://trips.tuniu.com/travelthread/0/1792142/%d/0', u'7'),
        (u'亚洲', u'斋普尔', u'http://trips.tuniu.com/travelthread/0/1741413/%d/0', u'6'),
        (u'亚洲', u'蓝毗尼', u'http://trips.tuniu.com/travelthread/0/45003/%d/0', u'7'),
        (u'亚洲', u'瓜拉丁加奴', u'http://trips.tuniu.com/travelthread/0/44304/%d/0', u'7'),
        (u'亚洲', u'康提', u'http://trips.tuniu.com/travelthread/0/1742630/%d/0', u'8'),
        (u'亚洲', u'顺化市', u'http://trips.tuniu.com/travelthread/0/784194/%d/0', u'6'),
        (u'亚洲', u'太宰府市', u'http://trips.tuniu.com/travelthread/0/784009/%d/0', u'6'),
        (u'亚洲', u'缅甸', u'http://trips.tuniu.com/travelthread/0/3909/%d/0', u'6'),
        (u'亚洲', u'春川市', u'http://trips.tuniu.com/travelthread/0/43662/%d/0', u'6'),
        (u'亚洲', u'平阳省', u'http://trips.tuniu.com/travelthread/0/784077/%d/0', u'6'),
        (u'亚洲', u'博卡拉', u'http://trips.tuniu.com/travelthread/0/1792114/%d/0', u'6'),
        (u'亚洲', u'滨松市', u'http://trips.tuniu.com/travelthread/0/784923/%d/0', u'6'),
        (u'亚洲', u'帕坦', u'http://trips.tuniu.com/travelthread/0/1792121/%d/0', u'6'),
        (u'亚洲', u'斗湖', u'http://trips.tuniu.com/travelthread/0/44386/%d/0', u'6'),
        (u'亚洲', u'美斯乐', u'http://trips.tuniu.com/travelthread/0/1792188/%d/0', u'6'),
        (u'亚洲', u'丹布勒', u'http://trips.tuniu.com/travelthread/0/786348/%d/0', u'6'),
        (u'亚洲', u'第一区', u'http://trips.tuniu.com/travelthread/0/784190/%d/0', u'5'),
        (u'亚洲', u'薄荷', u'http://trips.tuniu.com/travelthread/0/786897/%d/0', u'5'),
        (u'亚洲', u'新德里', u'http://trips.tuniu.com/travelthread/0/1741870/%d/0', u'8'),
        (u'亚洲', u'春武里', u'http://trips.tuniu.com/travelthread/0/45374/%d/0', u'5'),
        (u'亚洲', u'马六甲', u'http://trips.tuniu.com/travelthread/0/44333/%d/0', u'5'),
        (u'亚洲', u'布城', u'http://trips.tuniu.com/travelthread/0/785135/%d/0', u'7'),
        (u'亚洲', u'雅加达', u'http://trips.tuniu.com/travelthread/0/46037/%d/0', u'5'),
        (u'亚洲', u'岘港', u'http://trips.tuniu.com/travelthread/0/784180/%d/0', u'6'),
        (u'亚洲', u'宿务', u'http://trips.tuniu.com/travelthread/0/43503/%d/0', u'4'),
        (u'亚洲', u'仙本那', u'http://trips.tuniu.com/travelthread/0/44401/%d/0', u'6'),
        (u'亚洲', u'北揽', u'http://trips.tuniu.com/travelthread/0/45365/%d/0', u'4'),
        (u'亚洲', u'费利杜环礁', u'http://trips.tuniu.com/travelthread/0/44279/%d/0', u'4'),
        (u'亚洲', u'第三区', u'http://trips.tuniu.com/travelthread/0/784202/%d/0', u'4'),
        (u'亚洲', u'美奈', u'http://trips.tuniu.com/travelthread/0/786584/%d/0', u'6'),
        (u'亚洲', u'函馆市', u'http://trips.tuniu.com/travelthread/0/47178/%d/0', u'4'),
        (u'亚洲', u'曼德勒省', u'http://trips.tuniu.com/travelthread/0/44856/%d/0', u'4'),
        (u'亚洲', u'长野', u'http://trips.tuniu.com/travelthread/0/45137/%d/0', u'4'),
        (u'亚洲', u'京畿道', u'http://trips.tuniu.com/travelthread/0/43680/%d/0', u'4'),
        (u'亚洲', u'藩切市', u'http://trips.tuniu.com/travelthread/0/784231/%d/0', u'4'),
        (u'亚洲', u'巴亭郡', u'http://trips.tuniu.com/travelthread/0/784182/%d/0', u'4'),
        (u'亚洲', u'不丹', u'http://trips.tuniu.com/travelthread/0/3917/%d/0', u'4'),
        (u'亚洲', u'万象', u'http://trips.tuniu.com/travelthread/0/44168/%d/0', u'4'),
        (u'亚洲', u'焦特布尔', u'http://trips.tuniu.com/travelthread/0/1741391/%d/0', u'3'),
        (u'亚洲', u'静冈市', u'http://trips.tuniu.com/travelthread/0/784933/%d/0', u'3'),
        (u'亚洲', u'全罗北道', u'http://trips.tuniu.com/travelthread/0/43757/%d/0', u'3'),
        (u'亚洲', u'还剑郡', u'http://trips.tuniu.com/travelthread/0/784192/%d/0', u'3'),
        (u'亚洲', u'西哈努克市', u'http://trips.tuniu.com/travelthread/0/43984/%d/0', u'3'),
        (u'亚洲', u'浦安市', u'http://trips.tuniu.com/travelthread/0/784979/%d/0', u'3'),
        (u'亚洲', u'山梨', u'http://trips.tuniu.com/travelthread/0/45128/%d/0', u'3'),
        (u'亚洲', u'斋浦尔', u'http://trips.tuniu.com/travelthread/0/786967/%d/0', u'3'),
        (u'亚洲', u'忠清北道', u'http://trips.tuniu.com/travelthread/0/43798/%d/0', u'3'),
        (u'亚洲', u'阿苏市', u'http://trips.tuniu.com/travelthread/0/785035/%d/0', u'3'),
        (u'亚洲', u'多哈', u'http://trips.tuniu.com/travelthread/0/44020/%d/0', u'4'),
        (u'亚洲', u'芒街市', u'http://trips.tuniu.com/travelthread/0/784209/%d/0', u'3'),
        (u'亚洲', u'关丹', u'http://trips.tuniu.com/travelthread/0/44345/%d/0', u'3'),
        (u'亚洲', u'贺茂郡', u'http://trips.tuniu.com/travelthread/0/784911/%d/0', u'3'),
        (u'亚洲', u'那霸市', u'http://trips.tuniu.com/travelthread/0/784698/%d/0', u'4'),
        (u'亚洲', u'和歌山', u'http://trips.tuniu.com/travelthread/0/45113/%d/0', u'3'),
        (u'亚洲', u'比鲁兰', u'http://trips.tuniu.com/travelthread/0/44381/%d/0', u'4'),
        (u'亚洲', u'庆尚北道', u'http://trips.tuniu.com/travelthread/0/43712/%d/0', u'3'),
        (u'亚洲', u'占巴塞', u'http://trips.tuniu.com/travelthread/0/44170/%d/0', u'2'),
        (u'亚洲', u'蒙古', u'http://trips.tuniu.com/travelthread/0/3902/%d/0', u'2'),
        (u'亚洲', u'庆州市', u'http://trips.tuniu.com/travelthread/0/43725/%d/0', u'2'),
        (u'亚洲', u'朝鲜', u'http://trips.tuniu.com/travelthread/0/3903/%d/0', u'2'),
        (u'亚洲', u'庆尚南道', u'http://trips.tuniu.com/travelthread/0/43736/%d/0', u'2'),
        (u'欧洲', u'法国', u'http://trips.tuniu.com/travelthread/0/3604/%d/0', u'514'),
        (u'欧洲', u'德国', u'http://trips.tuniu.com/travelthread/0/3616/%d/0', u'253'),
        (u'欧洲', u'芬兰', u'http://trips.tuniu.com/travelthread/0/3611/%d/0', u'148'),
        (u'欧洲', u'挪威', u'http://trips.tuniu.com/travelthread/0/3612/%d/0', u'87'),
        (u'欧洲', u'瑞典', u'http://trips.tuniu.com/travelthread/0/3613/%d/0', u'54'),
        (u'欧洲', u'瑞士', u'http://trips.tuniu.com/travelthread/0/3619/%d/0', u'297'),
        (u'欧洲', u'俄罗斯', u'http://trips.tuniu.com/travelthread/0/3624/%d/0', u'245'),
        (u'欧洲', u'意大利', u'http://trips.tuniu.com/travelthread/0/3645/%d/0', u'274'),
        (u'欧洲', u'比利时', u'http://trips.tuniu.com/travelthread/0/3603/%d/0', u'113'),
        (u'欧洲', u'梵蒂冈', u'http://trips.tuniu.com/travelthread/0/3632/%d/0', u'267'),
        (u'欧洲', u'巴黎', u'http://trips.tuniu.com/travelthread/0/43479/%d/0', u'77'),
        (u'欧洲', u'英国', u'http://trips.tuniu.com/travelthread/0/3608/%d/0', u'107'),
        (u'欧洲', u'奥地利', u'http://trips.tuniu.com/travelthread/0/3614/%d/0', u'120'),
        (u'欧洲', u'维罗纳', u'http://trips.tuniu.com/travelthread/0/784569/%d/0', u'24'),
        (u'欧洲', u'捷克共和国', u'http://trips.tuniu.com/travelthread/0/3617/%d/0', u'77'),
        (u'欧洲', u'匈牙利', u'http://trips.tuniu.com/travelthread/0/3621/%d/0', u'26'),
        (u'欧洲', u'丹麦', u'http://trips.tuniu.com/travelthread/0/3610/%d/0', u'54'),
        (u'欧洲', u'希腊', u'http://trips.tuniu.com/travelthread/0/3643/%d/0', u'110'),
        (u'欧洲', u'荷兰', u'http://trips.tuniu.com/travelthread/0/3605/%d/0', u'89'),
        (u'欧洲', u'西班牙', u'http://trips.tuniu.com/travelthread/0/3644/%d/0', u'89'),
        (u'欧洲', u'卢森堡', u'http://trips.tuniu.com/travelthread/0/3606/%d/0', u'58'),
        (u'欧洲', u'列支敦士登', u'http://trips.tuniu.com/travelthread/0/3618/%d/0', u'41'),
        (u'欧洲', u'摩纳哥', u'http://trips.tuniu.com/travelthread/0/3607/%d/0', u'23'),
        (u'欧洲', u'罗马', u'http://trips.tuniu.com/travelthread/0/45958/%d/0', u'31'),
        (u'欧洲', u'圣彼得堡', u'http://trips.tuniu.com/travelthread/0/787372/%d/0', u'74'),
        (u'欧洲', u'莫斯科市', u'http://trips.tuniu.com/travelthread/0/787365/%d/0', u'73'),
        (u'欧洲', u'伦敦', u'http://trips.tuniu.com/travelthread/0/46085/%d/0', u'44'),
        (u'欧洲', u'威尼斯', u'http://trips.tuniu.com/travelthread/0/787072/%d/0', u'134'),
        (u'欧洲', u'卢塞恩', u'http://trips.tuniu.com/travelthread/0/785102/%d/0', u'124'),
        (u'欧洲', u'恩格尔贝格', u'http://trips.tuniu.com/travelthread/0/785106/%d/0', u'49'),
        (u'欧洲', u'佛罗伦萨', u'http://trips.tuniu.com/travelthread/0/787034/%d/0', u'119'),
        (u'欧洲', u'米兰', u'http://trips.tuniu.com/travelthread/0/787056/%d/0', u'57'),
        (u'欧洲', u'因特拉肯', u'http://trips.tuniu.com/travelthread/0/785530/%d/0', u'48'),
        (u'欧洲', u'比萨', u'http://trips.tuniu.com/travelthread/0/787030/%d/0', u'36'),
        (u'欧洲', u'雅典', u'http://trips.tuniu.com/travelthread/0/786773/%d/0', u'36'),
        (u'欧洲', u'卢达本纳', u'http://trips.tuniu.com/travelthread/0/785653/%d/0', u'34'),
        (u'欧洲', u'布鲁塞尔市', u'http://trips.tuniu.com/travelthread/0/1170339/%d/0', u'26'),
        (u'欧洲', u'法兰克福', u'http://trips.tuniu.com/travelthread/0/43318/%d/0', u'29'),
        (u'欧洲', u'阿姆斯特丹', u'http://trips.tuniu.com/travelthread/0/43830/%d/0', u'23'),
        (u'欧洲', u'蓬特雷西纳', u'http://trips.tuniu.com/travelthread/0/785594/%d/0', u'25'),
        (u'欧洲', u'维也纳', u'http://trips.tuniu.com/travelthread/0/784480/%d/0', u'25'),
        (u'欧洲', u'克罗地亚', u'http://trips.tuniu.com/travelthread/0/3633/%d/0', u'20'),
        (u'欧洲', u'日内瓦', u'http://trips.tuniu.com/travelthread/0/785100/%d/0', u'19'),
        (u'欧洲', u'慕尼黑', u'http://trips.tuniu.com/travelthread/0/43337/%d/0', u'20'),
        (u'欧洲', u'波兰', u'http://trips.tuniu.com/travelthread/0/3615/%d/0', u'17'),
        (u'欧洲', u'布拉格直辖市', u'http://trips.tuniu.com/travelthread/0/43988/%d/0', u'24'),
        (u'欧洲', u'基克拉泽斯', u'http://trips.tuniu.com/travelthread/0/786745/%d/0', u'18'),
        (u'欧洲', u'蒂罗尔', u'http://trips.tuniu.com/travelthread/0/42987/%d/0', u'16'),
        (u'欧洲', u'普罗旺斯', u'http://trips.tuniu.com/travelthread/0/47127/%d/0', u'16'),
        (u'欧洲', u'葡萄牙', u'http://trips.tuniu.com/travelthread/0/3638/%d/0', u'15'),
        (u'欧洲', u'柏林', u'http://trips.tuniu.com/travelthread/0/43306/%d/0', u'20'),
        (u'欧洲', u'伯尔尼', u'http://trips.tuniu.com/travelthread/0/785104/%d/0', u'14'),
        (u'欧洲', u'哥本哈根', u'http://trips.tuniu.com/travelthread/0/1170419/%d/0', u'13'),
        (u'欧洲', u'赫尔辛基', u'http://trips.tuniu.com/travelthread/0/1174441/%d/0', u'15'),
        (u'欧洲', u'布达佩斯', u'http://trips.tuniu.com/travelthread/0/45834/%d/0', u'15'),
        (u'欧洲', u'苏黎世', u'http://trips.tuniu.com/travelthread/0/785108/%d/0', u'14'),
        (u'欧洲', u'蒙特勒', u'http://trips.tuniu.com/travelthread/0/785645/%d/0', u'10'),
        (u'欧洲', u'拉脱维亚', u'http://trips.tuniu.com/travelthread/0/3625/%d/0', u'10'),
        (u'欧洲', u'斯德哥尔摩', u'http://trips.tuniu.com/travelthread/0/784792/%d/0', u'11'),
        (u'欧洲', u'因斯布鲁克', u'http://trips.tuniu.com/travelthread/0/784470/%d/0', u'11'),
        (u'欧洲', u'爱丁堡', u'http://trips.tuniu.com/travelthread/0/46051/%d/0', u'10'),
        (u'欧洲', u'基克拉迪', u'http://trips.tuniu.com/travelthread/0/45799/%d/0', u'8'),
        (u'欧洲', u'圣托里尼', u'http://trips.tuniu.com/travelthread/0/786813/%d/0', u'12'),
        (u'欧洲', u'萨尔茨堡', u'http://trips.tuniu.com/travelthread/0/42990/%d/0', u'9'),
        (u'欧洲', u'爱尔兰', u'http://trips.tuniu.com/travelthread/0/3602/%d/0', u'8'),
        (u'欧洲', u'巴塞罗那', u'http://trips.tuniu.com/travelthread/0/786236/%d/0', u'10'),
        (u'欧洲', u'剑桥', u'http://trips.tuniu.com/travelthread/0/46074/%d/0', u'14'),
        (u'欧洲', u'沙夫豪森', u'http://trips.tuniu.com/travelthread/0/785526/%d/0', u'7'),
        (u'欧洲', u'科隆', u'http://trips.tuniu.com/travelthread/0/43329/%d/0', u'7'),
        (u'欧洲', u'洛桑', u'http://trips.tuniu.com/travelthread/0/785682/%d/0', u'8'),
        (u'欧洲', u'巴黎省', u'http://trips.tuniu.com/travelthread/0/47129/%d/0', u'7'),
        (u'欧洲', u'马德里自治区', u'http://trips.tuniu.com/travelthread/0/1741914/%d/0', u'8'),
        (u'欧洲', u'锡耶纳', u'http://trips.tuniu.com/travelthread/0/784545/%d/0', u'9'),
        (u'欧洲', u'塞维利亚', u'http://trips.tuniu.com/travelthread/0/45787/%d/0', u'7'),
        (u'欧洲', u'那不勒斯', u'http://trips.tuniu.com/travelthread/0/787028/%d/0', u'8'),
        (u'欧洲', u'拉斯佩齐亚', u'http://trips.tuniu.com/travelthread/0/787062/%d/0', u'9'),
        (u'欧洲', u'巴塞尔', u'http://trips.tuniu.com/travelthread/0/785709/%d/0', u'7'),
        (u'欧洲', u'马拉加', u'http://trips.tuniu.com/travelthread/0/1741920/%d/0', u'7'),
        (u'欧洲', u'马德里', u'http://trips.tuniu.com/travelthread/0/45777/%d/0', u'5'),
        (u'欧洲', u'里斯本', u'http://trips.tuniu.com/travelthread/0/1742365/%d/0', u'12'),
        (u'欧洲', u'采尔马特', u'http://trips.tuniu.com/travelthread/0/785520/%d/0', u'4'),
        (u'欧洲', u'卢加诺', u'http://trips.tuniu.com/travelthread/0/785522/%d/0', u'7'),
        (u'欧洲', u'奥斯陆市', u'http://trips.tuniu.com/travelthread/0/45043/%d/0', u'4'),
        (u'欧洲', u'卢瓦尔-谢尔省', u'http://trips.tuniu.com/travelthread/0/47125/%d/0', u'4'),
        (u'欧洲', u'滨海边疆区', u'http://trips.tuniu.com/travelthread/0/784740/%d/0', u'5'),
        (u'欧洲', u'牛津', u'http://trips.tuniu.com/travelthread/0/46088/%d/0', u'5'),
        (u'欧洲', u'高地', u'http://trips.tuniu.com/travelthread/0/787083/%d/0', u'5'),
        (u'欧洲', u'坎布里亚', u'http://trips.tuniu.com/travelthread/0/787085/%d/0', u'4'),
        (u'欧洲', u'伊尔库茨克', u'http://trips.tuniu.com/travelthread/0/786184/%d/0', u'4'),
        (u'欧洲', u'萨格勒布', u'http://trips.tuniu.com/travelthread/0/44059/%d/0', u'4'),
        (u'欧洲', u'布拉迪斯拉发', u'http://trips.tuniu.com/travelthread/0/785141/%d/0', u'5'),
        (u'欧洲', u'萨拉戈萨', u'http://trips.tuniu.com/travelthread/0/45783/%d/0', u'4'),
        (u'欧洲', u'托莱多', u'http://trips.tuniu.com/travelthread/0/45793/%d/0', u'4'),
        (u'欧洲', u'马耳他', u'http://trips.tuniu.com/travelthread/0/3636/%d/0', u'3'),
        (u'欧洲', u'布列塔尼地区Bretagne', u'http://trips.tuniu.com/travelthread/0/786889/%d/0', u'3'),
        (u'欧洲', u'松恩－菲尤拉讷', u'http://trips.tuniu.com/travelthread/0/45055/%d/0', u'3'),
        (u'欧洲', u'法夫', u'http://trips.tuniu.com/travelthread/0/787081/%d/0', u'3'),
        (u'欧洲', u'斯洛伐克', u'http://trips.tuniu.com/travelthread/0/3620/%d/0', u'3'),
        (u'欧洲', u'卢布尔雅那', u'http://trips.tuniu.com/travelthread/0/786216/%d/0', u'3'),
        (u'欧洲', u'伦巴第', u'http://trips.tuniu.com/travelthread/0/784549/%d/0', u'3'),
        (u'欧洲', u'克拉科夫', u'http://trips.tuniu.com/travelthread/0/1740152/%d/0', u'3'),
        (u'欧洲', u'汝拉', u'http://trips.tuniu.com/travelthread/0/45174/%d/0', u'3'),
        (u'欧洲', u'圣克鲁斯-德特内里费', u'http://trips.tuniu.com/travelthread/0/45789/%d/0', u'3'),
        (u'欧洲', u'德累斯顿', u'http://trips.tuniu.com/travelthread/0/43315/%d/0', u'3'),
        (u'欧洲', u'马赛', u'http://trips.tuniu.com/travelthread/0/786121/%d/0', u'3'),
        (u'欧洲', u'伯明翰', u'http://trips.tuniu.com/travelthread/0/46065/%d/0', u'2'),
        (u'欧洲', u'代格', u'http://trips.tuniu.com/travelthread/0/784814/%d/0', u'2'),
        (u'欧洲', u'贝林佐纳', u'http://trips.tuniu.com/travelthread/0/785649/%d/0', u'2'),
        (u'欧洲', u'尼斯', u'http://trips.tuniu.com/travelthread/0/786148/%d/0', u'3'),
        (u'欧洲', u'巴伦西亚', u'http://trips.tuniu.com/travelthread/0/1741444/%d/0', u'3'),
        (u'欧洲', u'格林德尔瓦尔德', u'http://trips.tuniu.com/travelthread/0/785651/%d/0', u'2'),
        (u'欧洲', u'第戎', u'http://trips.tuniu.com/travelthread/0/786154/%d/0', u'2'),
        (u'欧洲', u'molenwaard', u'http://trips.tuniu.com/travelthread/0/1800746/%d/0', u'2'),
        (u'欧洲', u'卢森堡市', u'http://trips.tuniu.com/travelthread/0/786162/%d/0', u'3'),
        (u'欧洲', u'格拉纳达', u'http://trips.tuniu.com/travelthread/0/1741878/%d/0', u'2'),
        (u'欧洲', u'波尔沃', u'http://trips.tuniu.com/travelthread/0/1174503/%d/0', u'2'),
        (u'欧洲', u'科尔多瓦', u'http://trips.tuniu.com/travelthread/0/1741895/%d/0', u'3'),
        (u'欧洲', u'约克', u'http://trips.tuniu.com/travelthread/0/46110/%d/0', u'3'),
        (u'欧洲', u'克鲁姆洛夫', u'http://trips.tuniu.com/travelthread/0/784644/%d/0', u'4'),
        (u'欧洲', u'卡尔斯塔德', u'http://trips.tuniu.com/travelthread/0/1174756/%d/0', u'2'),
        (u'欧洲', u'卡尔卡松', u'http://trips.tuniu.com/travelthread/0/47141/%d/0', u'2'),
        (u'欧洲', u'威尔特', u'http://trips.tuniu.com/travelthread/0/787088/%d/0', u'3'),
        (u'欧洲', u'都柏林', u'http://trips.tuniu.com/travelthread/0/784776/%d/0', u'3'),
        (u'欧洲', u'利卡-塞尼', u'http://trips.tuniu.com/travelthread/0/44057/%d/0', u'2'),
        (u'欧洲', u'纳克索斯', u'http://trips.tuniu.com/travelthread/0/786747/%d/0', u'2'),
        (u'欧洲', u'库腾贝格', u'http://trips.tuniu.com/travelthread/0/1796232/%d/0', u'2'),
        (u'欧洲', u'华沙', u'http://trips.tuniu.com/travelthread/0/1740132/%d/0', u'3'),
        (u'欧洲', u'洛伊克巴德', u'http://trips.tuniu.com/travelthread/0/785610/%d/0', u'2'),
        (u'欧洲', u'符拉迪沃斯托克', u'http://trips.tuniu.com/travelthread/0/787355/%d/0', u'2'),
        (u'欧洲', u'图恩', u'http://trips.tuniu.com/travelthread/0/786024/%d/0', u'2'),
        (u'欧洲', u'格拉斯哥', u'http://trips.tuniu.com/travelthread/0/46053/%d/0', u'2'),
        (u'欧洲', u'大雷克雅未克区', u'http://trips.tuniu.com/travelthread/0/786094/%d/0', u'2'),
        (u'欧洲', u'罗马尼亚', u'http://trips.tuniu.com/travelthread/0/3634/%d/0', u'2'),
        (u'欧洲', u'英格兰', u'http://trips.tuniu.com/travelthread/0/46061/%d/0', u'2'),
        (u'欧洲', u'布里恩茨', u'http://trips.tuniu.com/travelthread/0/785635/%d/0', u'2'),
        (u'欧洲', u'波茨坦', u'http://trips.tuniu.com/travelthread/0/43309/%d/0', u'2'),
        (u'欧洲', u'南部区', u'http://trips.tuniu.com/travelthread/0/786109/%d/0', u'1'),
        (u'欧洲', u'巴斯', u'http://trips.tuniu.com/travelthread/0/46063/%d/0', u'1'),
        (u'欧洲', u'布莱德', u'http://trips.tuniu.com/travelthread/0/1742367/%d/0', u'1'),
        (u'欧洲', u'拉纳卡', u'http://trips.tuniu.com/travelthread/0/45238/%d/0', u'1'),
        (u'欧洲', u'斯洛文尼亚', u'http://trips.tuniu.com/travelthread/0/3639/%d/0', u'1'),
        (u'欧洲', u'格洛斯特', u'http://trips.tuniu.com/travelthread/0/46071/%d/0', u'1'),
        (u'欧洲', u'弗赖堡', u'http://trips.tuniu.com/travelthread/0/43319/%d/0', u'1'),
        (u'欧洲', u'里昂', u'http://trips.tuniu.com/travelthread/0/786150/%d/0', u'1'),
        (u'欧洲', u'塞尔维亚', u'http://trips.tuniu.com/travelthread/0/3641/%d/0', u'1'),
        (u'欧洲', u'汉堡', u'http://trips.tuniu.com/travelthread/0/43321/%d/0', u'1'),
        (u'欧洲', u'热那亚', u'http://trips.tuniu.com/travelthread/0/787070/%d/0', u'4'),
        (u'欧洲', u'弗拉基米尔州', u'http://trips.tuniu.com/travelthread/0/784736/%d/0', u'1'),
        (u'欧洲', u'日利纳', u'http://trips.tuniu.com/travelthread/0/45298/%d/0', u'1'),
        (u'欧洲', u'贝希特斯加登', u'http://trips.tuniu.com/travelthread/0/1793693/%d/0', u'1'),
        (u'欧洲', u'格蒙登', u'http://trips.tuniu.com/travelthread/0/784486/%d/0', u'3'),
        (u'欧洲', u'图尔库', u'http://trips.tuniu.com/travelthread/0/1174479/%d/0', u'1'),
        (u'欧洲', u'苏兹达尔', u'http://trips.tuniu.com/travelthread/0/784738/%d/0', u'1'),
        (u'欧洲', u'比尔森', u'http://trips.tuniu.com/travelthread/0/43987/%d/0', u'1'),
        (u'欧洲', u'曼彻斯特', u'http://trips.tuniu.com/travelthread/0/46086/%d/0', u'1'),
        (u'欧洲', u'吕贝克', u'http://trips.tuniu.com/travelthread/0/784492/%d/0', u'2'),
        (u'欧洲', u'劳塔兰皮 ', u'http://trips.tuniu.com/travelthread/0/1174499/%d/0', u'1'),
        (u'欧洲', u'马格德堡', u'http://trips.tuniu.com/travelthread/0/43333/%d/0', u'1'),
        (u'欧洲', u'梅尔克', u'http://trips.tuniu.com/travelthread/0/784508/%d/0', u'2'),
        (u'欧洲', u'上奥地利', u'http://trips.tuniu.com/travelthread/0/42991/%d/0', u'1'),
        (u'欧洲', u'卡罗维发利市', u'http://trips.tuniu.com/travelthread/0/784640/%d/0', u'2'),
        (u'欧洲', u'维茨瑙', u'http://trips.tuniu.com/travelthread/0/785686/%d/0', u'2'),
        (u'欧洲', u'曼海姆', u'http://trips.tuniu.com/travelthread/0/43334/%d/0', u'1'),
        (u'欧洲', u'雅罗斯拉夫尔州', u'http://trips.tuniu.com/travelthread/0/784744/%d/0', u'1'),
        (u'欧洲', u'塔林', u'http://trips.tuniu.com/travelthread/0/786182/%d/0', u'1'),
        (u'欧洲', u'卡罗维发利', u'http://trips.tuniu.com/travelthread/0/43990/%d/0', u'1'),
        (u'欧洲', u'阿维尼翁', u'http://trips.tuniu.com/travelthread/0/1794288/%d/0', u'2'),
        (u'欧洲', u'西西里', u'http://trips.tuniu.com/travelthread/0/784528/%d/0', u'2'),
        (u'欧洲', u'美因兹', u'http://trips.tuniu.com/travelthread/0/43335/%d/0', u'1'),
        (u'欧洲', u'欧登塞', u'http://trips.tuniu.com/travelthread/0/784766/%d/0', u'2'),
        (u'欧洲', u'托斯卡纳', u'http://trips.tuniu.com/travelthread/0/784543/%d/0', u'1'),
        (u'欧洲', u'希奥利艾', u'http://trips.tuniu.com/travelthread/0/1459213/%d/0', u'1'),
        (u'欧洲', u'鹿特丹', u'http://trips.tuniu.com/travelthread/0/1796193/%d/0', u'1'),
        (u'欧洲', u'莫尔日', u'http://trips.tuniu.com/travelthread/0/785580/%d/0', u'1'),
        (u'欧洲', u'布卢瓦', u'http://trips.tuniu.com/travelthread/0/47143/%d/0', u'1'),
        (u'欧洲', u'普罗夫迪夫', u'http://trips.tuniu.com/travelthread/0/43094/%d/0', u'1'),
        (u'欧洲', u'索非亚', u'http://trips.tuniu.com/travelthread/0/43095/%d/0', u'1'),
        (u'欧洲', u'赤塔', u'http://trips.tuniu.com/travelthread/0/1459250/%d/0', u'1'),
        (u'欧洲', u'莫斯科', u'http://trips.tuniu.com/travelthread/0/43411/%d/0', u'1'),
        (u'欧洲', u'比隆', u'http://trips.tuniu.com/travelthread/0/784778/%d/0', u'1'),
        (u'欧洲', u'施皮茨', u'http://trips.tuniu.com/travelthread/0/785586/%d/0', u'1'),
        (u'欧洲', u'索非亚市', u'http://trips.tuniu.com/travelthread/0/43096/%d/0', u'1'),
        (u'欧洲', u'赫尔辛格', u'http://trips.tuniu.com/travelthread/0/784790/%d/0', u'1'),
        (u'欧洲', u'东佛兰德', u'http://trips.tuniu.com/travelthread/0/43116/%d/0', u'1'),
        (u'欧洲', u'小波兰省', u'http://trips.tuniu.com/travelthread/0/1740150/%d/0', u'1'),
        (u'欧洲', u'保加利亚', u'http://trips.tuniu.com/travelthread/0/3631/%d/0', u'1'),
        (u'欧洲', u'苏格兰', u'http://trips.tuniu.com/travelthread/0/46049/%d/0', u'1'),
        (u'欧洲', u'海德堡', u'http://trips.tuniu.com/travelthread/0/784356/%d/0', u'2'),
        (u'欧洲', u'特维尔', u'http://trips.tuniu.com/travelthread/0/43430/%d/0', u'1'),
        (u'欧洲', u'伊拉克里翁', u'http://trips.tuniu.com/travelthread/0/786781/%d/0', u'2'),
        (u'欧洲', u'威尼托', u'http://trips.tuniu.com/travelthread/0/784567/%d/0', u'1'),
        (u'欧洲', u'沃韦', u'http://trips.tuniu.com/travelthread/0/785918/%d/0', u'1'),
        (u'欧洲', u'阿尔勒', u'http://trips.tuniu.com/travelthread/0/43475/%d/0', u'1'),
        (u'欧洲', u'卡尔斯库加', u'http://trips.tuniu.com/travelthread/0/784794/%d/0', u'1'),
        (u'欧洲', u'博洛尼亚', u'http://trips.tuniu.com/travelthread/0/1742281/%d/0', u'1'),
        (u'欧洲', u'冰岛', u'http://trips.tuniu.com/travelthread/0/3609/%d/0', u'1'),
        (u'欧洲', u'斯维尔德洛夫斯克州', u'http://trips.tuniu.com/travelthread/0/1740823/%d/0', u'1'),
        (u'欧洲', u'圣安德烈', u'http://trips.tuniu.com/travelthread/0/784800/%d/0', u'1'),
        (u'欧洲', u'里加', u'http://trips.tuniu.com/travelthread/0/44130/%d/0', u'1'),
        (u'北美洲', u'夏威夷', u'http://trips.tuniu.com/travelthread/0/44716/%d/0', u'34'),
        (u'北美洲', u'美国', u'http://trips.tuniu.com/travelthread/0/3738/%d/0', u'201'),
        (u'北美洲', u'纽约市', u'http://trips.tuniu.com/travelthread/0/44679/%d/0', u'104'),
        (u'北美洲', u'加拿大', u'http://trips.tuniu.com/travelthread/0/3710/%d/0', u'46'),
        (u'北美洲', u'科罗拉多', u'http://trips.tuniu.com/travelthread/0/44581/%d/0', u'27'),
        (u'北美洲', u'旧金山', u'http://trips.tuniu.com/travelthread/0/44557/%d/0', u'44'),
        (u'北美洲', u'纽约', u'http://trips.tuniu.com/travelthread/0/44676/%d/0', u'42'),
        (u'北美洲', u'怀俄明', u'http://trips.tuniu.com/travelthread/0/44549/%d/0', u'24'),
        (u'北美洲', u'洛杉矶', u'http://trips.tuniu.com/travelthread/0/44558/%d/0', u'51'),
        (u'北美洲', u'华盛顿哥伦比亚特区', u'http://trips.tuniu.com/travelthread/0/44544/%d/0', u'35'),
        (u'北美洲', u'檀香山', u'http://trips.tuniu.com/travelthread/0/44718/%d/0', u'22'),
        (u'北美洲', u'拉斯维加斯', u'http://trips.tuniu.com/travelthread/0/44673/%d/0', u'23'),
        (u'北美洲', u'多伦多', u'http://trips.tuniu.com/travelthread/0/43913/%d/0', u'14'),
        (u'北美洲', u'华盛顿', u'http://trips.tuniu.com/travelthread/0/44545/%d/0', u'13'),
        (u'北美洲', u'圣迭戈', u'http://trips.tuniu.com/travelthread/0/44559/%d/0', u'12'),
        (u'北美洲', u'芝加哥', u'http://trips.tuniu.com/travelthread/0/44759/%d/0', u'11'),
        (u'北美洲', u'盐湖城', u'http://trips.tuniu.com/travelthread/0/44772/%d/0', u'10'),
        (u'北美洲', u'哥伦比亚特区', u'http://trips.tuniu.com/travelthread/0/44543/%d/0', u'8'),
        (u'北美洲', u'内华达', u'http://trips.tuniu.com/travelthread/0/44667/%d/0', u'8'),
        (u'北美洲', u'渥太华', u'http://trips.tuniu.com/travelthread/0/43938/%d/0', u'7'),
        (u'北美洲', u'蒙特利尔', u'http://trips.tuniu.com/travelthread/0/786252/%d/0', u'10'),
        (u'北美洲', u'温哥华', u'http://trips.tuniu.com/travelthread/0/43935/%d/0', u'6'),
        (u'北美洲', u'犹他', u'http://trips.tuniu.com/travelthread/0/44764/%d/0', u'6'),
        (u'北美洲', u'艾伯塔', u'http://trips.tuniu.com/travelthread/0/786258/%d/0', u'6'),
        (u'北美洲', u'亚利桑那', u'http://trips.tuniu.com/travelthread/0/44733/%d/0', u'5'),
        (u'北美洲', u'密歇根', u'http://trips.tuniu.com/travelthread/0/44631/%d/0', u'5'),
        (u'北美洲', u'安大略', u'http://trips.tuniu.com/travelthread/0/784573/%d/0', u'5'),
        (u'北美洲', u'加利福尼亚', u'http://trips.tuniu.com/travelthread/0/44556/%d/0', u'5'),
        (u'北美洲', u'尼亚加拉', u'http://trips.tuniu.com/travelthread/0/784575/%d/0', u'5'),
        (u'北美洲', u'新泽西', u'http://trips.tuniu.com/travelthread/0/44729/%d/0', u'4'),
        (u'北美洲', u'费城', u'http://trips.tuniu.com/travelthread/0/44491/%d/0', u'7'),
        (u'北美洲', u'金斯敦', u'http://trips.tuniu.com/travelthread/0/43921/%d/0', u'4'),
        (u'北美洲', u'魁北克', u'http://trips.tuniu.com/travelthread/0/43923/%d/0', u'4'),
        (u'北美洲', u'布法罗', u'http://trips.tuniu.com/travelthread/0/44677/%d/0', u'8'),
        (u'北美洲', u'佛罗里达', u'http://trips.tuniu.com/travelthread/0/44529/%d/0', u'3'),
        (u'北美洲', u'南达科他', u'http://trips.tuniu.com/travelthread/0/44656/%d/0', u'3'),
        (u'北美洲', u'墨西哥', u'http://trips.tuniu.com/travelthread/0/3725/%d/0', u'3'),
        (u'北美洲', u'墨西哥城', u'http://trips.tuniu.com/travelthread/0/44905/%d/0', u'5'),
        (u'北美洲', u'维多利亚', u'http://trips.tuniu.com/travelthread/0/786256/%d/0', u'3'),
        (u'北美洲', u'班夫', u'http://trips.tuniu.com/travelthread/0/784591/%d/0', u'3'),
        (u'北美洲', u'马里兰', u'http://trips.tuniu.com/travelthread/0/44606/%d/0', u'2'),
        (u'北美洲', u'蒙大拿', u'http://trips.tuniu.com/travelthread/0/44614/%d/0', u'2'),
        (u'北美洲', u'奥兰多', u'http://trips.tuniu.com/travelthread/0/44530/%d/0', u'2'),
        (u'北美洲', u'不列颠哥伦比亚', u'http://trips.tuniu.com/travelthread/0/784563/%d/0', u'2'),
        (u'北美洲', u'欧胡岛', u'http://trips.tuniu.com/travelthread/0/1799538/%d/0', u'2'),
        (u'北美洲', u'耶洛奈夫', u'http://trips.tuniu.com/travelthread/0/43940/%d/0', u'1'),
        (u'北美洲', u'马坦萨斯', u'http://trips.tuniu.com/travelthread/0/43596/%d/0', u'1'),
        (u'北美洲', u'危地马拉省', u'http://trips.tuniu.com/travelthread/0/1741852/%d/0', u'1'),
        (u'北美洲', u'新奥尔良', u'http://trips.tuniu.com/travelthread/0/44597/%d/0', u'1'),
        (u'北美洲', u'宾夕法尼亚', u'http://trips.tuniu.com/travelthread/0/44489/%d/0', u'2'),
        (u'北美洲', u'北美洲', u'http://trips.tuniu.com/travelthread/0/3700/%d/0', u'1'),
        (u'北美洲', u'圣保罗', u'http://trips.tuniu.com/travelthread/0/44655/%d/0', u'1'),
        (u'北美洲', u'蒙特瑞', u'http://trips.tuniu.com/travelthread/0/1791820/%d/0', u'1'),
        (u'北美洲', u'迈阿密', u'http://trips.tuniu.com/travelthread/0/44535/%d/0', u'1'),
        (u'北美洲', u'古巴', u'http://trips.tuniu.com/travelthread/0/3713/%d/0', u'2'),
        (u'北美洲', u'内布拉斯加', u'http://trips.tuniu.com/travelthread/0/44663/%d/0', u'1'),
        (u'北美洲', u'危地马拉', u'http://trips.tuniu.com/travelthread/0/3720/%d/0', u'1'),
        (u'北美洲', u'克雷塔罗', u'http://trips.tuniu.com/travelthread/0/44891/%d/0', u'1'),
        (u'北美洲', u'西雅图', u'http://trips.tuniu.com/travelthread/0/44548/%d/0', u'1'),
        (u'北美洲', u'哈瓦那', u'http://trips.tuniu.com/travelthread/0/43592/%d/0', u'2'),
        (u'北美洲', u'圣斯皮里图斯', u'http://trips.tuniu.com/travelthread/0/43601/%d/0', u'1'),
        (u'北美洲', u'波士顿', u'http://trips.tuniu.com/travelthread/0/44611/%d/0', u'2'),
        (u'北美洲', u'圣地亚哥省', u'http://trips.tuniu.com/travelthread/0/43600/%d/0', u'2'),
        (u'北美洲', u'哈瓦那城', u'http://trips.tuniu.com/travelthread/0/43593/%d/0', u'1'),
        (u'北美洲', u'科迪', u'http://trips.tuniu.com/travelthread/0/1807905/%d/0', u'5'),
        (u'北美洲', u'阿布奎基', u'http://trips.tuniu.com/travelthread/0/1798647/%d/0', u'1'),
        (u'北美洲', u'帕洛阿尔托', u'http://trips.tuniu.com/travelthread/0/1799309/%d/0', u'2'),
        (u'北美洲', u'哈瓦苏湖市', u'http://trips.tuniu.com/travelthread/0/1798966/%d/0', u'1'),
        (u'北美洲', u'斯托克顿', u'http://trips.tuniu.com/travelthread/0/1799430/%d/0', u'1'),
        (u'北美洲', u'圣克拉拉市', u'http://trips.tuniu.com/travelthread/0/1816694/%d/0', u'1'),
        (u'北美洲', u'夏威夷县', u'http://trips.tuniu.com/travelthread/0/1799535/%d/0', u'2'),
        (u'北美洲', u'菲尼克斯', u'http://trips.tuniu.com/travelthread/0/1798906/%d/0', u'1'),
        (u'北美洲', u'佩奇', u'http://trips.tuniu.com/travelthread/0/1799314/%d/0', u'1'),
        (u'北美洲', u'安克雷奇', u'http://trips.tuniu.com/travelthread/0/44456/%d/0', u'1'),
        (u'大洋洲', u'塞班岛', u'http://trips.tuniu.com/travelthread/0/786461/%d/0', u'137'),
        (u'大洋洲', u'悉尼', u'http://trips.tuniu.com/travelthread/0/42985/%d/0', u'66'),
        (u'大洋洲', u'塞班市', u'http://trips.tuniu.com/travelthread/0/786459/%d/0', u'177'),
        (u'大洋洲', u'北马里亚纳群岛', u'http://trips.tuniu.com/travelthread/0/4114/%d/0', u'298'),
        (u'大洋洲', u'澳大利亚', u'http://trips.tuniu.com/travelthread/0/4102/%d/0', u'149'),
        (u'大洋洲', u'新西兰', u'http://trips.tuniu.com/travelthread/0/4103/%d/0', u'71'),
        (u'大洋洲', u'布里斯班', u'http://trips.tuniu.com/travelthread/0/42951/%d/0', u'39'),
        (u'大洋洲', u'墨尔本', u'http://trips.tuniu.com/travelthread/0/42973/%d/0', u'36'),
        (u'大洋洲', u'奥克兰', u'http://trips.tuniu.com/travelthread/0/1742970/%d/0', u'37'),
        (u'大洋洲', u'黄金海岸', u'http://trips.tuniu.com/travelthread/0/42952/%d/0', u'34'),
        (u'大洋洲', u'凯恩斯', u'http://trips.tuniu.com/travelthread/0/42953/%d/0', u'38'),
        (u'大洋洲', u'罗托路亚', u'http://trips.tuniu.com/travelthread/0/784250/%d/0', u'23'),
        (u'大洋洲', u'天宁岛', u'http://trips.tuniu.com/travelthread/0/786451/%d/0', u'18'),
        (u'大洋洲', u'皇后镇', u'http://trips.tuniu.com/travelthread/0/784252/%d/0', u'21'),
        (u'大洋洲', u'基督城', u'http://trips.tuniu.com/travelthread/0/786685/%d/0', u'21'),
        (u'大洋洲', u'斐济', u'http://trips.tuniu.com/travelthread/0/4108/%d/0', u'17'),
        (u'大洋洲', u'苏瓦', u'http://trips.tuniu.com/travelthread/0/786384/%d/0', u'14'),
        (u'大洋洲', u'关岛', u'http://trips.tuniu.com/travelthread/0/4115/%d/0', u'12'),
        (u'大洋洲', u'坎特伯雷', u'http://trips.tuniu.com/travelthread/0/784260/%d/0', u'10'),
        (u'大洋洲', u'惠灵顿', u'http://trips.tuniu.com/travelthread/0/784254/%d/0', u'10'),
        (u'大洋洲', u'帕劳群岛', u'http://trips.tuniu.com/travelthread/0/4113/%d/0', u'10'),
        (u'大洋洲', u'楠迪', u'http://trips.tuniu.com/travelthread/0/786396/%d/0', u'9'),
        (u'大洋洲', u'达尼丁', u'http://trips.tuniu.com/travelthread/0/1742977/%d/0', u'9'),
        (u'大洋洲', u'因弗卡吉尔', u'http://trips.tuniu.com/travelthread/0/1742978/%d/0', u'7'),
        (u'大洋洲', u'陶波', u'http://trips.tuniu.com/travelthread/0/784266/%d/0', u'7'),
        (u'大洋洲', u'昆士兰', u'http://trips.tuniu.com/travelthread/0/42950/%d/0', u'7'),
        (u'大洋洲', u'克赖斯特彻奇', u'http://trips.tuniu.com/travelthread/0/45818/%d/0', u'6'),
        (u'大洋洲', u'南地', u'http://trips.tuniu.com/travelthread/0/784262/%d/0', u'6'),
        (u'大洋洲', u'阿德莱德', u'http://trips.tuniu.com/travelthread/0/42958/%d/0', u'6'),
        (u'大洋洲', u'堪培拉', u'http://trips.tuniu.com/travelthread/0/42949/%d/0', u'5'),
        (u'大洋洲', u'奥塔哥', u'http://trips.tuniu.com/travelthread/0/784244/%d/0', u'5'),
        (u'大洋洲', u'南澳大利亚', u'http://trips.tuniu.com/travelthread/0/42957/%d/0', u'5'),
        (u'大洋洲', u'北领地', u'http://trips.tuniu.com/travelthread/0/786650/%d/0', u'4'),
        (u'大洋洲', u'所罗门群岛', u'http://trips.tuniu.com/travelthread/0/4105/%d/0', u'3'),
        (u'大洋洲', u'哈密尔顿', u'http://trips.tuniu.com/travelthread/0/1742996/%d/0', u'3'),
        (u'大洋洲', u'达尔文', u'http://trips.tuniu.com/travelthread/0/42947/%d/0', u'3'),
        (u'大洋洲', u'格雷茅斯', u'http://trips.tuniu.com/travelthread/0/1742997/%d/0', u'3'),
        (u'大洋洲', u'蒂阿瑙湖', u'http://trips.tuniu.com/travelthread/0/784278/%d/0', u'6'),
        (u'大洋洲', u'奥玛鲁', u'http://trips.tuniu.com/travelthread/0/784246/%d/0', u'3'),
        (u'大洋洲', u'塔斯马尼亚', u'http://trips.tuniu.com/travelthread/0/42966/%d/0', u'3'),
        (u'大洋洲', u'南方省', u'http://trips.tuniu.com/travelthread/0/786674/%d/0', u'2'),
        (u'大洋洲', u'西澳大利亚', u'http://trips.tuniu.com/travelthread/0/42974/%d/0', u'2'),
        (u'大洋洲', u'西岸', u'http://trips.tuniu.com/travelthread/0/784270/%d/0', u'2'),
        (u'大洋洲', u'莱克特卡波', u'http://trips.tuniu.com/travelthread/0/784282/%d/0', u'2'),
        (u'大洋洲', u'科罗尔', u'http://trips.tuniu.com/travelthread/0/786417/%d/0', u'3'),
        (u'大洋洲', u'奥托罗杭阿', u'http://trips.tuniu.com/travelthread/0/784310/%d/0', u'2'),
        (u'大洋洲', u'切尔巴切布', u'http://trips.tuniu.com/travelthread/0/786419/%d/0', u'5'),
        (u'大洋洲', u'丰盛湾', u'http://trips.tuniu.com/travelthread/0/784248/%d/0', u'2'),
        (u'大洋洲', u'珀斯', u'http://trips.tuniu.com/travelthread/0/42981/%d/0', u'1'),
        (u'大洋洲', u'瓦努阿图', u'http://trips.tuniu.com/travelthread/0/4106/%d/0', u'1'),
        (u'大洋洲', u'纳尔逊', u'http://trips.tuniu.com/travelthread/0/45821/%d/0', u'1'),
        (u'大洋洲', u'西部大区', u'http://trips.tuniu.com/travelthread/0/786378/%d/0', u'1'),
        (u'大洋洲', u'怀卡托', u'http://trips.tuniu.com/travelthread/0/784264/%d/0', u'1'),
        (u'大洋洲', u'霍克湾', u'http://trips.tuniu.com/travelthread/0/784272/%d/0', u'1'),
        (u'大洋洲', u'塔希提', u'http://trips.tuniu.com/travelthread/0/786638/%d/0', u'2'),
        (u'大洋洲', u'马塔马塔', u'http://trips.tuniu.com/travelthread/0/1797733/%d/0', u'1'),
        (u'大洋洲', u'维拉港', u'http://trips.tuniu.com/travelthread/0/786670/%d/0', u'1'),
        (u'大洋洲', u'梅莱凯奥克', u'http://trips.tuniu.com/travelthread/0/1814719/%d/0', u'14'),
        (u'大洋洲', u'克罗克卢贝', u'http://trips.tuniu.com/travelthread/0/1814749/%d/0', u'1'),
        (u'大洋洲', u'劳托卡', u'http://trips.tuniu.com/travelthread/0/786380/%d/0', u'2'),
        (u'大洋洲', u'阿罗敦', u'http://trips.tuniu.com/travelthread/0/784256/%d/0', u'1'),
        (u'大洋洲', u'北地大区', u'http://trips.tuniu.com/travelthread/0/784268/%d/0', u'1'),
        (u'大洋洲', u'汤斯维尔', u'http://trips.tuniu.com/travelthread/0/42955/%d/0', u'1'),
        (u'大洋洲', u'布拉布拉岛', u'http://trips.tuniu.com/travelthread/0/1797646/%d/0', u'1'),
        (u'南美洲', u'阿根廷', u'http://trips.tuniu.com/travelthread/0/3810/%d/0', u'7'),
        (u'南美洲', u'巴西', u'http://trips.tuniu.com/travelthread/0/3806/%d/0', u'4'),
        (u'南美洲', u'秘鲁', u'http://trips.tuniu.com/travelthread/0/3805/%d/0', u'4'),
        (u'南美洲', u'火地岛省', u'http://trips.tuniu.com/travelthread/0/785528/%d/0', u'2'),
        (u'南美洲', u'波哥大首都区', u'http://trips.tuniu.com/travelthread/0/43549/%d/0', u'1'),
        (u'南美洲', u'圣地亚哥', u'http://trips.tuniu.com/travelthread/0/786504/%d/0', u'2'),
        (u'南美洲', u'圣克鲁斯省', u'http://trips.tuniu.com/travelthread/0/785532/%d/0', u'1'),
        (u'南美洲', u'麦哲伦-智利南极大区', u'http://trips.tuniu.com/travelthread/0/46147/%d/0', u'1'),
        (u'南美洲', u'圣保罗市', u'http://trips.tuniu.com/travelthread/0/785592/%d/0', u'2'),
        (u'南美洲', u'布宜诺斯艾利斯', u'http://trips.tuniu.com/travelthread/0/42806/%d/0', u'1'),
        (u'南美洲', u'伊瓜苏', u'http://trips.tuniu.com/travelthread/0/785633/%d/0', u'1'),
        (u'南美洲', u'巴西利亚', u'http://trips.tuniu.com/travelthread/0/43059/%d/0', u'1'),
        (u'南美洲', u'利马', u'http://trips.tuniu.com/travelthread/0/786282/%d/0', u'1'),
        (u'南美洲', u'里奥夸尔托', u'http://trips.tuniu.com/travelthread/0/1742152/%d/0', u'1'),
        (u'非洲', u'南非', u'http://trips.tuniu.com/travelthread/0/4054/%d/0', u'91'),
        (u'非洲', u'埃及', u'http://trips.tuniu.com/travelthread/0/4002/%d/0', u'123'),
        (u'非洲', u'毛里求斯', u'http://trips.tuniu.com/travelthread/0/4049/%d/0', u'74'),
        (u'非洲', u'开罗', u'http://trips.tuniu.com/travelthread/0/42865/%d/0', u'81'),
        (u'非洲', u'卢克索', u'http://trips.tuniu.com/travelthread/0/787092/%d/0', u'83'),
        (u'非洲', u'肯尼亚', u'http://trips.tuniu.com/travelthread/0/4020/%d/0', u'28'),
        (u'非洲', u'红海省', u'http://trips.tuniu.com/travelthread/0/787104/%d/0', u'38'),
        (u'非洲', u'塞舌尔', u'http://trips.tuniu.com/travelthread/0/4048/%d/0', u'23'),
        (u'非洲', u'路易港区', u'http://trips.tuniu.com/travelthread/0/784833/%d/0', u'30'),
        (u'非洲', u'吉萨', u'http://trips.tuniu.com/travelthread/0/787098/%d/0', u'35'),
        (u'非洲', u'开普敦', u'http://trips.tuniu.com/travelthread/0/787308/%d/0', u'53'),
        (u'非洲', u'亚历山大', u'http://trips.tuniu.com/travelthread/0/787126/%d/0', u'35'),
        (u'非洲', u'比勒陀利亚', u'http://trips.tuniu.com/travelthread/0/787305/%d/0', u'26'),
        (u'非洲', u'太阳城', u'http://trips.tuniu.com/travelthread/0/787310/%d/0', u'26'),
        (u'非洲', u'约翰内斯堡', u'http://trips.tuniu.com/travelthread/0/787312/%d/0', u'25'),
        (u'非洲', u'阿斯旺', u'http://trips.tuniu.com/travelthread/0/787118/%d/0', u'30'),
        (u'非洲', u'纳罗克', u'http://trips.tuniu.com/travelthread/0/786415/%d/0', u'20'),
        (u'非洲', u'黑河区', u'http://trips.tuniu.com/travelthread/0/784842/%d/0', u'20'),
        (u'非洲', u'内罗毕', u'http://trips.tuniu.com/travelthread/0/786429/%d/0', u'19'),
        (u'非洲', u'梅鲁', u'http://trips.tuniu.com/travelthread/0/786409/%d/0', u'14'),
        (u'非洲', u'孟菲斯', u'http://trips.tuniu.com/travelthread/0/787096/%d/0', u'8'),
        (u'非洲', u'纳库鲁', u'http://trips.tuniu.com/travelthread/0/44097/%d/0', u'7'),
        (u'非洲', u'萨凡纳区', u'http://trips.tuniu.com/travelthread/0/787290/%d/0', u'6'),
        (u'非洲', u'东开普省', u'http://trips.tuniu.com/travelthread/0/784238/%d/0', u'5'),
        (u'非洲', u'中央', u'http://trips.tuniu.com/travelthread/0/44116/%d/0', u'4'),
        (u'非洲', u'外岛', u'http://trips.tuniu.com/travelthread/0/784828/%d/0', u'3'),
        (u'非洲', u'南迪', u'http://trips.tuniu.com/travelthread/0/44099/%d/0', u'3'),
        (u'非洲', u'卡耶亚多', u'http://trips.tuniu.com/travelthread/0/786467/%d/0', u'2'),
        (u'非洲', u'普拉兰岛', u'http://trips.tuniu.com/travelthread/0/787288/%d/0', u'2'),
        (u'非洲', u'马埃岛', u'http://trips.tuniu.com/travelthread/0/784836/%d/0', u'2'),
        (u'非洲', u'圣路易', u'http://trips.tuniu.com/travelthread/0/45233/%d/0', u'1'),
        (u'非洲', u'埃德夫', u'http://trips.tuniu.com/travelthread/0/787120/%d/0', u'1'),
        (u'非洲', u'拉穆', u'http://trips.tuniu.com/travelthread/0/786457/%d/0', u'1'),
        (u'非洲', u'洪加达', u'http://trips.tuniu.com/travelthread/0/787153/%d/0', u'8'),
        (u'非洲', u'勒斯滕堡', u'http://trips.tuniu.com/travelthread/0/1792870/%d/0', u'1'),
        (u'非洲', u'突尼斯', u'http://trips.tuniu.com/travelthread/0/787172/%d/0', u'1'),
        (u'非洲', u'亚的斯亚贝巴', u'http://trips.tuniu.com/travelthread/0/786366/%d/0', u'1'),
        (u'非洲', u'乞力马扎罗', u'http://trips.tuniu.com/travelthread/0/45449/%d/0', u'1'),
        (u'非洲', u'尼亚胡鲁鲁', u'http://trips.tuniu.com/travelthread/0/786469/%d/0', u'1'),
        (u'非洲', u'庞波慕斯区', u'http://trips.tuniu.com/travelthread/0/784846/%d/0', u'1'),
        (u'非洲', u'居尔皮普', u'http://trips.tuniu.com/travelthread/0/784850/%d/0', u'1'),
        (u'非洲', u'克尼斯纳', u'http://trips.tuniu.com/travelthread/0/787316/%d/0', u'1'),
        (u'非洲', u'苏亚克', u'http://trips.tuniu.com/travelthread/0/1814652/%d/0', u'3'),
        (u'非洲', u'尼耶利', u'http://trips.tuniu.com/travelthread/0/786423/%d/0', u'1'),
        (u'非洲', u'伊希约洛', u'http://trips.tuniu.com/travelthread/0/786446/%d/0', u'1'),
        (u'非洲', u'路易港', u'http://trips.tuniu.com/travelthread/0/1814646/%d/0', u'8'),
        (u'非洲', u'里维耶尔德桑吉耶', u'http://trips.tuniu.com/travelthread/0/1817359/%d/0', u'2'),
        (u'非洲', u'马埃堡', u'http://trips.tuniu.com/travelthread/0/784840/%d/0', u'3'),
        (u'非洲', u'博尚', u'http://trips.tuniu.com/travelthread/0/1816720/%d/0', u'6'),
        (u'非洲', u'沙穆尼', u'http://trips.tuniu.com/travelthread/0/1816704/%d/0', u'1'),
        (u'非洲', u'庞普勒穆斯', u'http://trips.tuniu.com/travelthread/0/1816708/%d/0', u'1'),
        (u'非洲', u'沙马雷勒', u'http://trips.tuniu.com/travelthread/0/1816716/%d/0', u'1'),
        (u'非洲', u'贾米拉', u'http://trips.tuniu.com/travelthread/0/1816757/%d/0', u'1'),
        (u'非洲', u'塔马兰', u'http://trips.tuniu.com/travelthread/0/1814629/%d/0', u'1'),
        (u'非洲', u'苏伊士', u'http://trips.tuniu.com/travelthread/0/787102/%d/0', u'1'),
        (u'非洲', u'卡斯卡韦勒', u'http://trips.tuniu.com/travelthread/0/1816712/%d/0', u'1'),
        (u'非洲', u'塞伦盖蒂', u'http://trips.tuniu.com/travelthread/0/786479/%d/0', u'1'),
    )

    comment_api = 'http://www.tuniu.com/yii.php?r=trips/notesAjax/getreplylist'

    HEADERS = {
        'Host' : 'trips.tuniu.com',
        'Accept' : 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8',
        'Accept-Encoding' : 'gzip, deflate, sdch',
        'Accept-Language' : 'en-US,en;q=0.8,zh-CN;q=0.6,zh;q=0.4,zh-TW;q=0.2,ja;q=0.2',
        'Referer' : 'http://trips.tuniu.com/'
    }

    COMMENT_HEADERS = {
        'Accept' : 'application/json, text/javascript, */*; q=0.01',
        'Accept-Encoding' : 'gzip, deflate',
        'Accept-Language' : 'en-US,en;q=0.8,zh-CN;q=0.6,zh;q=0.4,zh-TW;q=0.2,ja;q=0.2',
        'Cache-Control' : 'max-age=0',
        'Connection' : 'keep-alive',
        'Content-Type' : 'application/x-www-form-urlencoded; charset=UTF-8',
        'Host' : 'www.tuniu.com',
        'Origin' : 'http://www.tuniu.com',
        'X-Requested-With' : 'XMLHttpRequest'
    }

    def start_requests(self):
        for youji in self.youji_api:
            meta = {
                'first_class' : youji[0],
                'second_class' : youji[1],
            }
            for page in range(int(youji[3])/12):
                yield Request(youji[2] % (page + 1), meta=meta, headers=self.HEADERS, dont_filter=True, callback=self.parse_youji)
                self.HEADERS.update({'Referer' : youji[2] % (page)})

    def parse_youji(self, response):
        meta = response.meta
        selector = Selector(response)
        for youji in selector.xpath('//div[@class="hot-main-square clearfix"]'):
            title = youji.xpath('./div[@class="hot-main-up"]/a/@title').extract_first()
            url = youji.xpath('./div[@class="hot-main-up"]/a/@href').extract_first()
            count_str = ''.join(youji.xpath('./div[@class="hot-main-middle"]/p[2]/node()').extract())
            match_result = re.match(r'^.*?(?P<view_count>\d+).*?(?P<love_count>\d+).*?(?P<comment_count>\d+).*?$',
                                    count_str,
                                    re.DOTALL)
            if not match_result:
                self.logger.error('failed to retrieve count data for url : %s' % response.url)
                continue
            counts = match_result.groupdict()
            view_count = counts.get('view_count')
            love_count = counts.get('love_count')
            comment_count = counts.get('comment_count')
            author = youji.xpath('./div[@class="hot-main-down"]/p/a/em/text()').extract_first()
            date = youji.xpath('./div[@class="hot-main-down"]/p/span/span/text()').extract_first() + ' 00:00:00'
            result = {
                'first_class' : meta['first_class'],
                'second_class' : meta['second_class'],
                'title' : title,
                'url' : url,
                'view_count' : view_count,
                'love_count' : love_count,
                'comment_count' : comment_count,
                'author' : author,
                'date' : date
            }
            if comment_count != '0':
                meta = response.meta.copy()
                meta['result'] = result

                travel_id_match = re.match('^.*trips/(\d+).*$', url)
                if not travel_id_match:
                    self.logger.error('failed to extract travel_id for url : %s' %  url)
                    continue
                travelId = travel_id_match.group(1)
                formdata = {
                    'travelId' : travelId,
                    'page' : '1',
                    'IsLookAuthor' : '0',
                    'ReplyPageSize' : '30'
                }
                self.COMMENT_HEADERS.update({'Referer' : url})
                yield FormRequest(self.comment_api, headers=self.COMMENT_HEADERS, formdata=formdata, meta=meta, callback=self.parse_comments)


    def parse_comments(self, response):
        meta = response.meta
        try:
            comment_data = json.loads(response.body_as_unicode())
        except Exception:
            self.logger.error('invalid result for tuniu comments')
            return
        else:
            if not comment_data.get('success'):
                self.logger.error('invalid result for tuniu comments')
                return
            html = comment_data.get('data')
            selector = Selector(text=html)
            comments = []
            for comment_item in selector.xpath('//div[@class="commentary-co clearfix"]'):
                author = comment_item.xpath('.//div[@class="commentary-center clearfix"]/p[@class="author-name"]/a/text()').extract_first()
                date = comment_item.xpath('.//div[@class="commentary-center clearfix"]/p[2]/em[2]/text()').extract_first()
                content = comment_item.xpath('.//div[@class="commentary-center clearfix"]/p[@class="commentary-txt"]/text()').extract_first()
                comments.append({
                    'author' : author,
                    'date' : date,
                    'content' : content
                })
            result = meta['result']
            result['comments'] = comments
            self.logger.info('tuniu youji : %s' % json.dumps(result, ensure_ascii=False).encode('utf-8'))



#class QunarBBSSpider(scrapy.Spider):
#    name = 'qunar_bbs'
#
#    bbs_api = (
#        (u'聪明旅行家专区', u'分享', 'http://travel.qunar.com/bbs/forum.php?mod=forumdisplay&fid=56&filter=typeid&typeid=28&orderby=views&page=%d', 13),
#        (u'聪明旅行家专区', u'组团', 'http://travel.qunar.com/bbs/forum.php?mod=forumdisplay&fid=56&filter=typeid&typeid=29&orderby=views&page=%d', 17),
#        (u'旅游问答', u'国内', 'http://travel.qunar.com/bbs/forum.php?mod=forumdisplay&fid=54&filter=typeid&typeid=17&orderby=views&page=%d', 577),
#        (u'旅游问答', u'东南亚', 'http://travel.qunar.com/bbs/forum.php?mod=forumdisplay&fid=54&filter=typeid&typeid=18&orderby=views&page=%d', 135),
#        (u'旅游问答', u'欧洲', 'http://travel.qunar.com/bbs/forum.php?mod=forumdisplay&fid=54&filter=typeid&typeid=19&orderby=views&page=%d', 112),
#        (u'旅游问答', u'美洲', 'http://travel.qunar.com/bbs/forum.php?mod=forumdisplay&fid=54&filter=typeid&typeid=20&orderby=views&page=%d', 29),
#        (u'旅游问答', u'大洋洲', 'http://travel.qunar.com/bbs/forum.php?mod=forumdisplay&fid=54&filter=typeid&typeid=21&orderby=views&page=%d', 24),
#        (u'精彩游记', u'国内游', 'http://travel.qunar.com/bbs/forum.php?mod=forumdisplay&fid=42&typeid=3&orderby=views&typeid=3&orderby=views&filter=typeid&page=%d', 168),
#        (u'精彩游记', u'港澳台', 'http://travel.qunar.com/bbs/forum.php?mod=forumdisplay&fid=42&filter=typeid&typeid=4&orderby=views&page=%d', 12),
#        (u'精彩游记', u'出境游', 'http://travel.qunar.com/bbs/forum.php?mod=forumdisplay&fid=42&filter=typeid&typeid=5&orderby=views&page=%d', 52),
#    )
#
#    HEADERS = {
#        'Host' : 'travel.qunar.com',
#        'Accept' : 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8',
#        'Accept-Encoding' : 'gzip, deflate, sdch',
#        'Accept-Language' : 'en-US,en;q=0.8,zh-CN;q=0.6,zh;q=0.4,zh-TW;q=0.2,ja;q=0.2'
#    }
#
#    def start_requests(self):
#        for gonglue_item in self.bbs_api:
#            meta = {}
#            meta['main_class'] = gonglue_item[0]
#            meta['second_class'] = gonglue_item[1]
#            for page in range(gonglue_item[3]):
#                yield Request(gonglue_item[2] % (page + 1), meta=meta, headers=self.HEADERS, dont_filter=True, callback=self.parse_list)
#
#    def parse_list(self, response):
#        meta = response.meta
#        body = re.sub(r'(<tbody id="normalthread_\d+")', r'\g<1>>', response.body_as_unicode())
#        selector = Selector(text=body)
#        for tiezi in selector.xpath('//table[@id="threadlisttableid"]/tbody[position()>1]/tr/th'):
#            title = tiezi.xpath('./span[@class="xst"]/a/text()').extract_first()
#            author = tiezi.xpath('./p[@class="mtn xg1"]/a[1]/text()').extract_first()
#            date = tiezi.xpath('./p[@class="mtn xg1"]/span/text()').extract_first()
#            view_count_text = ''.join(tiezi.xpath('./p[@class="mtn xg1"]/node()').extract())
#            view_count = re.search(u'(?<=查看: )\d+', view_count_text).group(0)
#            reply_count = tiezi.xpath('./p[@class="mtn xg1"]/a[2]/text()').extract_first()
#            url = 'http://travel.qunar.com/bbs/' + tiezi.xpath('./span[@class="xst"]/a/@href').extract_first()
#            data = {
#                'main_class' : meta['main_class'],
#                'second_class' : meta['second_class'],
#                'title' : title,
#                'author' : author,
#                'date' : date,
#                'view_count' : view_count,
#                'reply_count' : reply_count,
#                'url' : url
#            }
#            yield Request(url, meta={'data':data}, headers=self.HEADERS, dont_filter=True, callback=self.parse_content)
#
#    def parse_content(self, response):
#        data = response.meta['data']
#        selector = Selector(response)
#        replies = []
#        for post in selector.xpath('//div[@id="postlist"]//td[@class="plc"]'):
#            time = post.xpath('.//div[@class="authi"]/em/text()').extract_first()
#            content = ''.join(post.xpath('.//div[@class="t_fsz"]/node()').extract())
#            if not time or not content:
#                continue
#            replies.append({
#                'time' : time,
#                'content' : content
#            })
#        if replies:
#            data['content'] = replies[0]['content']
#            data['replies'] = replies[1:]
#        self.logger.info('qunar bbs: %s' % json.dumps(data, ensure_ascii=False).encode('utf-8'))
#
#
